/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package disasterrecovery

import (
	"context"

	disasterrecoveryv1beta1 "github.com/oracle/oci-service-operator/api/disasterrecovery/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DrPlanReconciler reconciles a DrPlan object.
type DrPlanReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=disasterrecovery.oracle.com,resources=drplans,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=disasterrecovery.oracle.com,resources=drplans/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=disasterrecovery.oracle.com,resources=drplans/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *DrPlanReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	drPlan := &disasterrecoveryv1beta1.DrPlan{}
	return r.Reconciler.Reconcile(ctx, req, drPlan)
}

// SetupWithManager sets up the controller with the Manager.
func (r *DrPlanReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&disasterrecoveryv1beta1.DrPlan{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
