/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by osok-api-generator. DO NOT EDIT.

package ons

import (
	"context"
	onsv1beta1 "github.com/oracle/oci-service-operator/api/ons/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
)

// TopicReconciler reconciles a Topic object
type TopicReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=ons.oracle.com,resources=topics,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=ons.oracle.com,resources=topics/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=ons.oracle.com,resources=topics/finalizers,verbs=update
// +kubebuilder:rbac:groups=,resources=events,verbs=get;list;watch;create;update;patch;delete

// Reconcile is part of the main kubernetes reconciliation loop which aims to
// move the current state of the cluster closer to the desired state.
func (r *TopicReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	resource := &onsv1beta1.Topic{}
	return r.Reconciler.Reconcile(ctx, req, resource)
}

// SetupWithManager sets up the controller with the Manager.
func (r *TopicReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&onsv1beta1.Topic{}).
		WithEventFilter(predicate.GenerationChangedPredicate{}).
		Complete(r)
}
