/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by osok-api-generator. DO NOT EDIT.

package services

import (
	onscontrollers "github.com/oracle/oci-service-operator/controllers/ons"
	"github.com/oracle/oci-service-operator/pkg/core"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/manager"
	confirmsubscription "github.com/oracle/oci-service-operator/pkg/servicemanager/ons/confirmsubscription"
	subscription "github.com/oracle/oci-service-operator/pkg/servicemanager/ons/subscription"
	topic "github.com/oracle/oci-service-operator/pkg/servicemanager/ons/topic"
	unsubscription "github.com/oracle/oci-service-operator/pkg/servicemanager/ons/unsubscription"
	ctrl "sigs.k8s.io/controller-runtime"
)

// ONS registers the generated reconcilers with the shared manager.
func ONS() manager.RegisterFunc {
	return func(mgr ctrl.Manager, deps *manager.Dependencies) error {
		if err := (&onscontrollers.TopicReconciler{
			Reconciler: &core.BaseReconciler{
				Client:             mgr.GetClient(),
				OSOKServiceManager: topic.NewTopicServiceManager(deps.Provider, deps.CredClient, deps.Scheme, loggerutil.OSOKLogger{Logger: ctrl.Log.WithName("service-manager").WithName("Topic")}, deps.Metrics),
				Finalizer:          core.NewBaseFinalizer(mgr.GetClient(), ctrl.Log),
				Log:                loggerutil.OSOKLogger{Logger: ctrl.Log.WithName("controllers").WithName("Topic")},
				Metrics:            deps.Metrics,
				Recorder:           mgr.GetEventRecorderFor("Topic"),
				Scheme:             deps.Scheme,
			},
		}).SetupWithManager(mgr); err != nil {
			return err
		}
		if err := (&onscontrollers.SubscriptionReconciler{
			Reconciler: &core.BaseReconciler{
				Client:             mgr.GetClient(),
				OSOKServiceManager: subscription.NewSubscriptionServiceManager(deps.Provider, deps.CredClient, deps.Scheme, loggerutil.OSOKLogger{Logger: ctrl.Log.WithName("service-manager").WithName("Subscription")}, deps.Metrics),
				Finalizer:          core.NewBaseFinalizer(mgr.GetClient(), ctrl.Log),
				Log:                loggerutil.OSOKLogger{Logger: ctrl.Log.WithName("controllers").WithName("Subscription")},
				Metrics:            deps.Metrics,
				Recorder:           mgr.GetEventRecorderFor("Subscription"),
				Scheme:             deps.Scheme,
			},
		}).SetupWithManager(mgr); err != nil {
			return err
		}
		if err := (&onscontrollers.ConfirmSubscriptionReconciler{
			Reconciler: &core.BaseReconciler{
				Client:             mgr.GetClient(),
				OSOKServiceManager: confirmsubscription.NewConfirmSubscriptionServiceManager(deps.Provider, deps.CredClient, deps.Scheme, loggerutil.OSOKLogger{Logger: ctrl.Log.WithName("service-manager").WithName("ConfirmSubscription")}, deps.Metrics),
				Finalizer:          core.NewBaseFinalizer(mgr.GetClient(), ctrl.Log),
				Log:                loggerutil.OSOKLogger{Logger: ctrl.Log.WithName("controllers").WithName("ConfirmSubscription")},
				Metrics:            deps.Metrics,
				Recorder:           mgr.GetEventRecorderFor("ConfirmSubscription"),
				Scheme:             deps.Scheme,
			},
		}).SetupWithManager(mgr); err != nil {
			return err
		}
		if err := (&onscontrollers.UnsubscriptionReconciler{
			Reconciler: &core.BaseReconciler{
				Client:             mgr.GetClient(),
				OSOKServiceManager: unsubscription.NewUnsubscriptionServiceManager(deps.Provider, deps.CredClient, deps.Scheme, loggerutil.OSOKLogger{Logger: ctrl.Log.WithName("service-manager").WithName("Unsubscription")}, deps.Metrics),
				Finalizer:          core.NewBaseFinalizer(mgr.GetClient(), ctrl.Log),
				Log:                loggerutil.OSOKLogger{Logger: ctrl.Log.WithName("controllers").WithName("Unsubscription")},
				Metrics:            deps.Metrics,
				Recorder:           mgr.GetEventRecorderFor("Unsubscription"),
				Scheme:             deps.Scheme,
			},
		}).SetupWithManager(mgr); err != nil {
			return err
		}
		return nil
	}
}
