/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package registrations

import (
	"fmt"

	generativeaiagentv1beta1 "github.com/oracle/oci-service-operator/api/generativeaiagent/v1beta1"
	generativeaiagentcontrollers "github.com/oracle/oci-service-operator/controllers/generativeaiagent"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generativeaiagentagentservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/generativeaiagent/agent"
	generativeaiagentagentendpointservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/generativeaiagent/agentendpoint"
	generativeaiagentdatasourceservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/generativeaiagent/datasource"
	generativeaiagentknowledgebaseservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/generativeaiagent/knowledgebase"
)

func init() {
	registerGeneratedGroup(GroupRegistration{
		Group:       "generativeaiagent",
		AddToScheme: generativeaiagentv1beta1.AddToScheme,
		SetupWithManager: func(ctx Context) error {
			if err := (&generativeaiagentcontrollers.AgentReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"Agent",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return generativeaiagentagentservicemanager.NewAgentServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup Agent controller: %w", err)
			}
			if err := (&generativeaiagentcontrollers.AgentEndpointReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"AgentEndpoint",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return generativeaiagentagentendpointservicemanager.NewAgentEndpointServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup AgentEndpoint controller: %w", err)
			}
			if err := (&generativeaiagentcontrollers.DataSourceReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"DataSource",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return generativeaiagentdatasourceservicemanager.NewDataSourceServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup DataSource controller: %w", err)
			}
			if err := (&generativeaiagentcontrollers.KnowledgeBaseReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"KnowledgeBase",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return generativeaiagentknowledgebaseservicemanager.NewKnowledgeBaseServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup KnowledgeBase controller: %w", err)
			}
			return nil
		},
	})
}
