/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package registrations

import (
	"fmt"

	identityv1beta1 "github.com/oracle/oci-service-operator/api/identity/v1beta1"
	identitycontrollers "github.com/oracle/oci-service-operator/controllers/identity"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	identityuserservicemanager "github.com/oracle/oci-service-operator/pkg/servicemanager/identity/user"
)

func init() {
	registerGeneratedGroup(GroupRegistration{
		Group:       "identity",
		AddToScheme: identityv1beta1.AddToScheme,
		SetupWithManager: func(ctx Context) error {
			if err := (&identitycontrollers.UserReconciler{
				Reconciler: NewBaseReconciler(
					ctx,
					"User",
					func(deps servicemanager.RuntimeDeps) servicemanager.OSOKServiceManager {
						return identityuserservicemanager.NewUserServiceManagerWithDeps(deps)
					},
				),
			}).SetupWithManager(ctx.Manager); err != nil {
				return fmt.Errorf("setup User controller: %w", err)
			}
			return nil
		},
	})
}
