/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package opensearch

import (
	"context"

	opensearchv1beta1 "github.com/oracle/oci-service-operator/api/opensearch/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
)

// OpensearchOpensearchClusterReconciler reconciles a OpensearchOpensearchCluster object.
type OpensearchOpensearchClusterReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=opensearch.oracle.com,resources=opensearchopensearchclusters,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=opensearch.oracle.com,resources=opensearchopensearchclusters/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=opensearch.oracle.com,resources=opensearchopensearchclusters/finalizers,verbs=update

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *OpensearchOpensearchClusterReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	opensearchOpensearchCluster := &opensearchv1beta1.OpensearchOpensearchCluster{}
	return r.Reconciler.Reconcile(ctx, req, opensearchOpensearchCluster)
}

// SetupWithManager sets up the controller with the Manager.
func (r *OpensearchOpensearchClusterReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&opensearchv1beta1.OpensearchOpensearchCluster{})
	return builder.
		WithEventFilter(predicate.GenerationChangedPredicate{}).
		Complete(r)
}
