/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MediaWorkflowConfigurationSpec defines the desired state of MediaWorkflowConfiguration.
type MediaWorkflowConfigurationSpec struct {
	// MediaWorkflowConfiguration identifier. Avoid entering confidential information.
	// +kubebuilder:validation:Required
	DisplayName string `json:"displayName"`
	// Reuseable parameter values encoded as a JSON; the top and second level JSON elements are
	// objects. Each key of the top level object refers to a task key that is unqiue to the
	// workflow, each of the second level objects' keys refer to the name of a parameter that is
	// unique to the task. taskKey -> parameterName -> parameterValue
	// +kubebuilder:validation:Required
	Parameters map[string]shared.JSONValue `json:"parameters"`
	// Compartment Identifier.
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
	// Example: `{"bar-key": "value"}`
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"foo-namespace": {"bar-key": "value"}}`
	// +kubebuilder:validation:Optional
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// Locks associated with this resource.
	// +kubebuilder:validation:Optional
	Locks []MediaWorkflowConfigurationLock `json:"locks,omitempty"`
}

// MediaWorkflowConfigurationLock defines nested fields for MediaWorkflowConfiguration.Lock.
type MediaWorkflowConfigurationLock struct {
	// Type of the lock.
	// +kubebuilder:validation:Required
	Type string `json:"type"`
	// The compartment ID of the lock.
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// The ID of the resource that is locking this resource. Indicates that deleting this resource will remove the lock.
	// +kubebuilder:validation:Optional
	RelatedResourceId string `json:"relatedResourceId,omitempty"`
	// A message added by the creator of the lock. This is typically used to give an
	// indication of why the resource is locked.
	// +kubebuilder:validation:Optional
	Message string `json:"message,omitempty"`
	// When the lock was created.
	// +kubebuilder:validation:Optional
	TimeCreated string `json:"timeCreated,omitempty"`
}

// MediaWorkflowConfigurationStatus defines the observed state of MediaWorkflowConfiguration.
type MediaWorkflowConfigurationStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// Unique identifier that is immutable on creation.
	Id string `json:"id,omitempty"`
	// Display name for the MediaWorkflowConfiguration. Avoid entering confidential information.
	DisplayName string `json:"displayName,omitempty"`
	// Compartment Identifier.
	CompartmentId string `json:"compartmentId,omitempty"`
	// Reuseable parameter values encoded as a JSON; the top and second level JSON elements are
	// objects. Each key of the top level object refer to a task key that is unqiue to the
	// workflow, each of the second level objects' keys refer to the name of a parameter that is
	// unique to the task. taskKey -> parameterName -> parameterValue
	Parameters map[string]shared.JSONValue `json:"parameters,omitempty"`
	// The time when the the MediaWorkflowConfiguration was created. An RFC3339 formatted datetime string.
	TimeCreated string `json:"timeCreated,omitempty"`
	// The time when the MediaWorkflowConfiguration was updated. An RFC3339 formatted datetime string.
	TimeUpdated string `json:"timeUpdated,omitempty"`
	// The current state of the MediaWorkflowConfiguration.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// A message describing the current state in more detail. For example, can be used to provide actionable information for a resource in Failed state.
	LifecyleDetails string `json:"lifecyleDetails,omitempty"`
	// Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
	// Example: `{"bar-key": "value"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"foo-namespace": {"bar-key": "value"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// Usage of system tag keys. These predefined keys are scoped to namespaces.
	// Example: `{"orcl-cloud": {"free-tier-retained": "true"}}`
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
	// Locks associated with this resource.
	Locks []MediaWorkflowConfigurationLock `json:"locks,omitempty"`
	// A message describing the current state in more detail. For example, can be used to provide actionable information for a resource in Failed state.
	LifecycleDetails string `json:"lifecycleDetails,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="DisplayName",type="string",JSONPath=".spec.displayName",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the MediaWorkflowConfiguration",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the MediaWorkflowConfiguration",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// MediaWorkflowConfiguration is the Schema for the mediaworkflowconfigurations API.
type MediaWorkflowConfiguration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MediaWorkflowConfigurationSpec   `json:"spec,omitempty"`
	Status MediaWorkflowConfigurationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// MediaWorkflowConfigurationList contains a list of MediaWorkflowConfiguration.
type MediaWorkflowConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MediaWorkflowConfiguration `json:"items"`
}

func init() {
	SchemeBuilder.Register(&MediaWorkflowConfiguration{}, &MediaWorkflowConfigurationList{})
}
