/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package opensearchopensearchcluster

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	opensearchv1beta1 "github.com/oracle/oci-service-operator/api/opensearch/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type OpensearchOpensearchClusterServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client OpensearchOpensearchClusterServiceClient
}

var _ servicemanager.OSOKServiceManager = (*OpensearchOpensearchClusterServiceManager)(nil)

func NewOpensearchOpensearchClusterServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *OpensearchOpensearchClusterServiceManager {
	manager := &OpensearchOpensearchClusterServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newOpensearchOpensearchClusterServiceClient(manager)
	return manager
}

func NewOpensearchOpensearchClusterServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *OpensearchOpensearchClusterServiceManager {
	return NewOpensearchOpensearchClusterServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *OpensearchOpensearchClusterServiceManager) WithClient(client OpensearchOpensearchClusterServiceClient) *OpensearchOpensearchClusterServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *OpensearchOpensearchClusterServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *OpensearchOpensearchClusterServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *OpensearchOpensearchClusterServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *OpensearchOpensearchClusterServiceManager) convert(obj runtime.Object) (*opensearchv1beta1.OpensearchOpensearchCluster, error) {
	resource, ok := obj.(*opensearchv1beta1.OpensearchOpensearchCluster)
	if !ok {
		return nil, fmt.Errorf("expected *opensearchv1beta1.OpensearchOpensearchCluster, got %T", obj)
	}
	return resource, nil
}

func (c *OpensearchOpensearchClusterServiceManager) status(resource *opensearchv1beta1.OpensearchOpensearchCluster) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
