/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// JmsPluginSpec defines the desired state of JmsPlugin.
type JmsPluginSpec struct {
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Management Agent (OMA), the Oracle Cloud Agent (OCA),
	// or the Oracle Container Management Agent (OCMA) instance where the JMS plugin is deployed.
	// +kubebuilder:validation:Required
	AgentId string `json:"agentId"`
	// The OMA/OCA/OCMA agent's compartment OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// The agent type.
	// +kubebuilder:validation:Optional
	AgentType string `json:"agentType,omitempty"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the fleet.
	// +kubebuilder:validation:Optional
	FleetId string `json:"fleetId,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"foo-namespace": {"bar-key": "value"}}`. (See Understanding Free-form Tags (https://docs.oracle.com/iaas/Content/Tagging/Tasks/managingtagsandtagnamespaces.htm)).
	// +kubebuilder:validation:Optional
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// Simple key-value pair that is applied without any predefined name, type, or scope. Exists for cross-compatibility only.
	// Example: `{"bar-key": "value"}`. (See Managing Tags and Tag Namespaces (https://docs.oracle.com/iaas/Content/Tagging/Concepts/understandingfreeformtags.htm).)
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
}

// JmsPluginStatus defines the observed state of JmsPlugin.
type JmsPluginStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) to identify this JmsPlugin.
	Id string `json:"id,omitempty"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the Management Agent (OMA), the Oracle Cloud Agent (OCA), or the Oracle Container Management Agent (OCMA)
	// instance where the JMS plugin is deployed.
	AgentId string `json:"agentId,omitempty"`
	// The agent type.
	AgentType string `json:"agentType,omitempty"`
	// The lifecycle state.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// The availability status.
	AvailabilityStatus string `json:"availabilityStatus,omitempty"`
	// The date and time the plugin was registered.
	TimeRegistered string `json:"timeRegistered,omitempty"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the fleet.
	FleetId string `json:"fleetId,omitempty"`
	// The OMA/OCA/OCMA agent's compartment OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm).
	CompartmentId string `json:"compartmentId,omitempty"`
	// The hostname of the agent.
	Hostname string `json:"hostname,omitempty"`
	// The operating system family for the plugin.
	OsFamily string `json:"osFamily,omitempty"`
	// The architecture of the operating system of the plugin.
	OsArchitecture string `json:"osArchitecture,omitempty"`
	// The distribution of the operating system of the plugin.
	OsDistribution string `json:"osDistribution,omitempty"`
	// The version of the plugin.
	PluginVersion string `json:"pluginVersion,omitempty"`
	// The date and time the resource was _last_ reported to JMS.
	// This is potentially _after_ the specified time period provided by the filters.
	// For example, a resource can be last reported to JMS before the start of a specified time period,
	// if it is also reported during the time period.
	TimeLastSeen string `json:"timeLastSeen,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"foo-namespace": {"bar-key": "value"}}`. (See Understanding Free-form Tags (https://docs.oracle.com/iaas/Content/Tagging/Tasks/managingtagsandtagnamespaces.htm)).
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// Simple key-value pair that is applied without any predefined name, type, or scope. Exists for cross-compatibility only.
	// Example: `{"bar-key": "value"}`. (See Managing Tags and Tag Namespaces (https://docs.oracle.com/iaas/Content/Tagging/Concepts/understandingfreeformtags.htm).)
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// System tags for this resource. Each key is predefined and scoped to a namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// System tags can be viewed by users, but can only be created by the system.
	// Example: `{"orcl-cloud": {"free-tier-retained": "true"}}`
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the JmsPlugin",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the JmsPlugin",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// JmsPlugin is the Schema for the jmsplugins API.
type JmsPlugin struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   JmsPluginSpec   `json:"spec,omitempty"`
	Status JmsPluginStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// JmsPluginList contains a list of JmsPlugin.
type JmsPluginList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []JmsPlugin `json:"items"`
}

func init() {
	SchemeBuilder.Register(&JmsPlugin{}, &JmsPluginList{})
}
