---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - generativeaiagent.oracle.com
  resources:
  - agentendpoints
  - agents
  - datasources
  - knowledgebases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - generativeaiagent.oracle.com
  resources:
  - agentendpoints/finalizers
  - agents/finalizers
  - datasources/finalizers
  - knowledgebases/finalizers
  verbs:
  - update
- apiGroups:
  - generativeaiagent.oracle.com
  resources:
  - agentendpoints/status
  - agents/status
  - datasources/status
  - knowledgebases/status
  verbs:
  - get
  - patch
  - update
