//go:build !ignore_autogenerated

/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/oracle/oci-service-operator/pkg/shared"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Assessment) DeepCopyInto(out *Assessment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Assessment.
func (in *Assessment) DeepCopy() *Assessment {
	if in == nil {
		return nil
	}
	out := new(Assessment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Assessment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentExcludeObject) DeepCopyInto(out *AssessmentExcludeObject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentExcludeObject.
func (in *AssessmentExcludeObject) DeepCopy() *AssessmentExcludeObject {
	if in == nil {
		return nil
	}
	out := new(AssessmentExcludeObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentIncludeObject) DeepCopyInto(out *AssessmentIncludeObject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentIncludeObject.
func (in *AssessmentIncludeObject) DeepCopy() *AssessmentIncludeObject {
	if in == nil {
		return nil
	}
	out := new(AssessmentIncludeObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentList) DeepCopyInto(out *AssessmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Assessment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentList.
func (in *AssessmentList) DeepCopy() *AssessmentList {
	if in == nil {
		return nil
	}
	out := new(AssessmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AssessmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentSourceDatabaseConnection) DeepCopyInto(out *AssessmentSourceDatabaseConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentSourceDatabaseConnection.
func (in *AssessmentSourceDatabaseConnection) DeepCopy() *AssessmentSourceDatabaseConnection {
	if in == nil {
		return nil
	}
	out := new(AssessmentSourceDatabaseConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentSpec) DeepCopyInto(out *AssessmentSpec) {
	*out = *in
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	out.SourceDatabaseConnection = in.SourceDatabaseConnection
	out.TargetDatabaseConnection = in.TargetDatabaseConnection
	if in.ExcludeObjects != nil {
		in, out := &in.ExcludeObjects, &out.ExcludeObjects
		*out = make([]AssessmentExcludeObject, len(*in))
		copy(*out, *in)
	}
	if in.IncludeObjects != nil {
		in, out := &in.IncludeObjects, &out.IncludeObjects
		*out = make([]AssessmentIncludeObject, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentSpec.
func (in *AssessmentSpec) DeepCopy() *AssessmentSpec {
	if in == nil {
		return nil
	}
	out := new(AssessmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentStatus) DeepCopyInto(out *AssessmentStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	out.SourceDatabaseConnection = in.SourceDatabaseConnection
	out.TargetDatabaseConnection = in.TargetDatabaseConnection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentStatus.
func (in *AssessmentStatus) DeepCopy() *AssessmentStatus {
	if in == nil {
		return nil
	}
	out := new(AssessmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AssessmentTargetDatabaseConnection) DeepCopyInto(out *AssessmentTargetDatabaseConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AssessmentTargetDatabaseConnection.
func (in *AssessmentTargetDatabaseConnection) DeepCopy() *AssessmentTargetDatabaseConnection {
	if in == nil {
		return nil
	}
	out := new(AssessmentTargetDatabaseConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connection) DeepCopyInto(out *Connection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connection.
func (in *Connection) DeepCopy() *Connection {
	if in == nil {
		return nil
	}
	out := new(Connection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Connection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionAdditionalAttribute) DeepCopyInto(out *ConnectionAdditionalAttribute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionAdditionalAttribute.
func (in *ConnectionAdditionalAttribute) DeepCopy() *ConnectionAdditionalAttribute {
	if in == nil {
		return nil
	}
	out := new(ConnectionAdditionalAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionIngressIp) DeepCopyInto(out *ConnectionIngressIp) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionIngressIp.
func (in *ConnectionIngressIp) DeepCopy() *ConnectionIngressIp {
	if in == nil {
		return nil
	}
	out := new(ConnectionIngressIp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionList) DeepCopyInto(out *ConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Connection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionList.
func (in *ConnectionList) DeepCopy() *ConnectionList {
	if in == nil {
		return nil
	}
	out := new(ConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSpec) DeepCopyInto(out *ConnectionSpec) {
	*out = *in
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.NsgIds != nil {
		in, out := &in.NsgIds, &out.NsgIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalAttributes != nil {
		in, out := &in.AdditionalAttributes, &out.AdditionalAttributes
		*out = make([]ConnectionAdditionalAttribute, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSpec.
func (in *ConnectionSpec) DeepCopy() *ConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionStatus) DeepCopyInto(out *ConnectionStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.IngressIps != nil {
		in, out := &in.IngressIps, &out.IngressIps
		*out = make([]ConnectionIngressIp, len(*in))
		copy(*out, *in)
	}
	if in.NsgIds != nil {
		in, out := &in.NsgIds, &out.NsgIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalAttributes != nil {
		in, out := &in.AdditionalAttributes, &out.AdditionalAttributes
		*out = make([]ConnectionAdditionalAttribute, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionStatus.
func (in *ConnectionStatus) DeepCopy() *ConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Migration) DeepCopyInto(out *Migration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Migration.
func (in *Migration) DeepCopy() *Migration {
	if in == nil {
		return nil
	}
	out := new(Migration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Migration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationAdvancedParameter) DeepCopyInto(out *MigrationAdvancedParameter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationAdvancedParameter.
func (in *MigrationAdvancedParameter) DeepCopy() *MigrationAdvancedParameter {
	if in == nil {
		return nil
	}
	out := new(MigrationAdvancedParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationAdvisorSettings) DeepCopyInto(out *MigrationAdvisorSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationAdvisorSettings.
func (in *MigrationAdvisorSettings) DeepCopy() *MigrationAdvisorSettings {
	if in == nil {
		return nil
	}
	out := new(MigrationAdvisorSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationDataTransferMediumDetails) DeepCopyInto(out *MigrationDataTransferMediumDetails) {
	*out = *in
	out.ObjectStorageBucket = in.ObjectStorageBucket
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationDataTransferMediumDetails.
func (in *MigrationDataTransferMediumDetails) DeepCopy() *MigrationDataTransferMediumDetails {
	if in == nil {
		return nil
	}
	out := new(MigrationDataTransferMediumDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationDataTransferMediumDetailsObjectStorageBucket) DeepCopyInto(out *MigrationDataTransferMediumDetailsObjectStorageBucket) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationDataTransferMediumDetailsObjectStorageBucket.
func (in *MigrationDataTransferMediumDetailsObjectStorageBucket) DeepCopy() *MigrationDataTransferMediumDetailsObjectStorageBucket {
	if in == nil {
		return nil
	}
	out := new(MigrationDataTransferMediumDetailsObjectStorageBucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationDataTransferMediumDetailsSource) DeepCopyInto(out *MigrationDataTransferMediumDetailsSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationDataTransferMediumDetailsSource.
func (in *MigrationDataTransferMediumDetailsSource) DeepCopy() *MigrationDataTransferMediumDetailsSource {
	if in == nil {
		return nil
	}
	out := new(MigrationDataTransferMediumDetailsSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationDataTransferMediumDetailsTarget) DeepCopyInto(out *MigrationDataTransferMediumDetailsTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationDataTransferMediumDetailsTarget.
func (in *MigrationDataTransferMediumDetailsTarget) DeepCopy() *MigrationDataTransferMediumDetailsTarget {
	if in == nil {
		return nil
	}
	out := new(MigrationDataTransferMediumDetailsTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationExcludeObject) DeepCopyInto(out *MigrationExcludeObject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationExcludeObject.
func (in *MigrationExcludeObject) DeepCopy() *MigrationExcludeObject {
	if in == nil {
		return nil
	}
	out := new(MigrationExcludeObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationGgsDetails) DeepCopyInto(out *MigrationGgsDetails) {
	*out = *in
	out.Replicat = in.Replicat
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationGgsDetails.
func (in *MigrationGgsDetails) DeepCopy() *MigrationGgsDetails {
	if in == nil {
		return nil
	}
	out := new(MigrationGgsDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationGgsDetailsExtract) DeepCopyInto(out *MigrationGgsDetailsExtract) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationGgsDetailsExtract.
func (in *MigrationGgsDetailsExtract) DeepCopy() *MigrationGgsDetailsExtract {
	if in == nil {
		return nil
	}
	out := new(MigrationGgsDetailsExtract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationGgsDetailsGgsDeployment) DeepCopyInto(out *MigrationGgsDetailsGgsDeployment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationGgsDetailsGgsDeployment.
func (in *MigrationGgsDetailsGgsDeployment) DeepCopy() *MigrationGgsDetailsGgsDeployment {
	if in == nil {
		return nil
	}
	out := new(MigrationGgsDetailsGgsDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationGgsDetailsReplicat) DeepCopyInto(out *MigrationGgsDetailsReplicat) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationGgsDetailsReplicat.
func (in *MigrationGgsDetailsReplicat) DeepCopy() *MigrationGgsDetailsReplicat {
	if in == nil {
		return nil
	}
	out := new(MigrationGgsDetailsReplicat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationHubDetails) DeepCopyInto(out *MigrationHubDetails) {
	*out = *in
	out.RestAdminCredentials = in.RestAdminCredentials
	out.Extract = in.Extract
	out.Replicat = in.Replicat
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationHubDetails.
func (in *MigrationHubDetails) DeepCopy() *MigrationHubDetails {
	if in == nil {
		return nil
	}
	out := new(MigrationHubDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationHubDetailsExtract) DeepCopyInto(out *MigrationHubDetailsExtract) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationHubDetailsExtract.
func (in *MigrationHubDetailsExtract) DeepCopy() *MigrationHubDetailsExtract {
	if in == nil {
		return nil
	}
	out := new(MigrationHubDetailsExtract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationHubDetailsObservedState) DeepCopyInto(out *MigrationHubDetailsObservedState) {
	*out = *in
	out.RestAdminCredentials = in.RestAdminCredentials
	out.Extract = in.Extract
	out.Replicat = in.Replicat
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationHubDetailsObservedState.
func (in *MigrationHubDetailsObservedState) DeepCopy() *MigrationHubDetailsObservedState {
	if in == nil {
		return nil
	}
	out := new(MigrationHubDetailsObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationHubDetailsReplicat) DeepCopyInto(out *MigrationHubDetailsReplicat) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationHubDetailsReplicat.
func (in *MigrationHubDetailsReplicat) DeepCopy() *MigrationHubDetailsReplicat {
	if in == nil {
		return nil
	}
	out := new(MigrationHubDetailsReplicat)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationHubDetailsRestAdminCredentials) DeepCopyInto(out *MigrationHubDetailsRestAdminCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationHubDetailsRestAdminCredentials.
func (in *MigrationHubDetailsRestAdminCredentials) DeepCopy() *MigrationHubDetailsRestAdminCredentials {
	if in == nil {
		return nil
	}
	out := new(MigrationHubDetailsRestAdminCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationHubDetailsRestAdminCredentialsObservedState) DeepCopyInto(out *MigrationHubDetailsRestAdminCredentialsObservedState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationHubDetailsRestAdminCredentialsObservedState.
func (in *MigrationHubDetailsRestAdminCredentialsObservedState) DeepCopy() *MigrationHubDetailsRestAdminCredentialsObservedState {
	if in == nil {
		return nil
	}
	out := new(MigrationHubDetailsRestAdminCredentialsObservedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationIncludeObject) DeepCopyInto(out *MigrationIncludeObject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationIncludeObject.
func (in *MigrationIncludeObject) DeepCopy() *MigrationIncludeObject {
	if in == nil {
		return nil
	}
	out := new(MigrationIncludeObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationInitialLoadSettings) DeepCopyInto(out *MigrationInitialLoadSettings) {
	*out = *in
	if in.Compatibility != nil {
		in, out := &in.Compatibility, &out.Compatibility
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationInitialLoadSettings.
func (in *MigrationInitialLoadSettings) DeepCopy() *MigrationInitialLoadSettings {
	if in == nil {
		return nil
	}
	out := new(MigrationInitialLoadSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationInitialLoadSettingsDataPumpParameters) DeepCopyInto(out *MigrationInitialLoadSettingsDataPumpParameters) {
	*out = *in
	if in.ExcludeParameters != nil {
		in, out := &in.ExcludeParameters, &out.ExcludeParameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationInitialLoadSettingsDataPumpParameters.
func (in *MigrationInitialLoadSettingsDataPumpParameters) DeepCopy() *MigrationInitialLoadSettingsDataPumpParameters {
	if in == nil {
		return nil
	}
	out := new(MigrationInitialLoadSettingsDataPumpParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationInitialLoadSettingsExportDirectoryObject) DeepCopyInto(out *MigrationInitialLoadSettingsExportDirectoryObject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationInitialLoadSettingsExportDirectoryObject.
func (in *MigrationInitialLoadSettingsExportDirectoryObject) DeepCopy() *MigrationInitialLoadSettingsExportDirectoryObject {
	if in == nil {
		return nil
	}
	out := new(MigrationInitialLoadSettingsExportDirectoryObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationInitialLoadSettingsImportDirectoryObject) DeepCopyInto(out *MigrationInitialLoadSettingsImportDirectoryObject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationInitialLoadSettingsImportDirectoryObject.
func (in *MigrationInitialLoadSettingsImportDirectoryObject) DeepCopy() *MigrationInitialLoadSettingsImportDirectoryObject {
	if in == nil {
		return nil
	}
	out := new(MigrationInitialLoadSettingsImportDirectoryObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationInitialLoadSettingsMetadataRemap) DeepCopyInto(out *MigrationInitialLoadSettingsMetadataRemap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationInitialLoadSettingsMetadataRemap.
func (in *MigrationInitialLoadSettingsMetadataRemap) DeepCopy() *MigrationInitialLoadSettingsMetadataRemap {
	if in == nil {
		return nil
	}
	out := new(MigrationInitialLoadSettingsMetadataRemap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationInitialLoadSettingsTablespaceDetails) DeepCopyInto(out *MigrationInitialLoadSettingsTablespaceDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationInitialLoadSettingsTablespaceDetails.
func (in *MigrationInitialLoadSettingsTablespaceDetails) DeepCopy() *MigrationInitialLoadSettingsTablespaceDetails {
	if in == nil {
		return nil
	}
	out := new(MigrationInitialLoadSettingsTablespaceDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationList) DeepCopyInto(out *MigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Migration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationList.
func (in *MigrationList) DeepCopy() *MigrationList {
	if in == nil {
		return nil
	}
	out := new(MigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationSpec) DeepCopyInto(out *MigrationSpec) {
	*out = *in
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	out.DataTransferMediumDetails = in.DataTransferMediumDetails
	in.InitialLoadSettings.DeepCopyInto(&out.InitialLoadSettings)
	out.AdvisorSettings = in.AdvisorSettings
	if in.ExcludeObjects != nil {
		in, out := &in.ExcludeObjects, &out.ExcludeObjects
		*out = make([]MigrationExcludeObject, len(*in))
		copy(*out, *in)
	}
	if in.IncludeObjects != nil {
		in, out := &in.IncludeObjects, &out.IncludeObjects
		*out = make([]MigrationIncludeObject, len(*in))
		copy(*out, *in)
	}
	out.HubDetails = in.HubDetails
	out.GgsDetails = in.GgsDetails
	if in.AdvancedParameters != nil {
		in, out := &in.AdvancedParameters, &out.AdvancedParameters
		*out = make([]MigrationAdvancedParameter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationSpec.
func (in *MigrationSpec) DeepCopy() *MigrationSpec {
	if in == nil {
		return nil
	}
	out := new(MigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationStatus) DeepCopyInto(out *MigrationStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	out.DataTransferMediumDetails = in.DataTransferMediumDetails
	in.InitialLoadSettings.DeepCopyInto(&out.InitialLoadSettings)
	out.AdvisorSettings = in.AdvisorSettings
	out.HubDetails = in.HubDetails
	out.GgsDetails = in.GgsDetails
	if in.AdvancedParameters != nil {
		in, out := &in.AdvancedParameters, &out.AdvancedParameters
		*out = make([]MigrationAdvancedParameter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationStatus.
func (in *MigrationStatus) DeepCopy() *MigrationStatus {
	if in == nil {
		return nil
	}
	out := new(MigrationStatus)
	in.DeepCopyInto(out)
	return out
}
