/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package jmsplugin

import (
	"context"

	jmssdk "github.com/oracle/oci-go-sdk/v65/jms"
	jmsv1beta1 "github.com/oracle/oci-service-operator/api/jms/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type JmsPluginRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *jmsv1beta1.JmsPlugin, string) (any, error)
	BuildUpdateBody func(context.Context, *jmsv1beta1.JmsPlugin, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*jmsv1beta1.JmsPlugin]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*jmsv1beta1.JmsPlugin]
	StatusHooks         generatedruntime.StatusHooks[*jmsv1beta1.JmsPlugin]
	ParityHooks         generatedruntime.ParityHooks[*jmsv1beta1.JmsPlugin]
	Async               generatedruntime.AsyncHooks[*jmsv1beta1.JmsPlugin]
	DeleteHooks         generatedruntime.DeleteHooks[*jmsv1beta1.JmsPlugin]
	Create              runtimeOperationHooks[jmssdk.CreateJmsPluginRequest, jmssdk.CreateJmsPluginResponse]
	Get                 runtimeOperationHooks[jmssdk.GetJmsPluginRequest, jmssdk.GetJmsPluginResponse]
	List                runtimeOperationHooks[jmssdk.ListJmsPluginsRequest, jmssdk.ListJmsPluginsResponse]
	Update              runtimeOperationHooks[jmssdk.UpdateJmsPluginRequest, jmssdk.UpdateJmsPluginResponse]
	Delete              runtimeOperationHooks[jmssdk.DeleteJmsPluginRequest, jmssdk.DeleteJmsPluginResponse]
	WrapGeneratedClient []func(JmsPluginServiceClient) JmsPluginServiceClient
}

type JmsPluginRuntimeHooksMutator func(*JmsPluginServiceManager, *JmsPluginRuntimeHooks)

var jmspluginRuntimeHooksMutators []JmsPluginRuntimeHooksMutator

func registerJmsPluginRuntimeHooksMutator(mutator JmsPluginRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	jmspluginRuntimeHooksMutators = append(jmspluginRuntimeHooksMutators, mutator)
}
func newJmsPluginRuntimeSemantics() *generatedruntime.Semantics {
	return &generatedruntime.Semantics{
		FormalService: "jms",
		FormalSlug:    "jmsplugin",
		Async: &generatedruntime.AsyncSemantics{
			Strategy:             "lifecycle",
			Runtime:              "generatedruntime",
			FormalClassification: "lifecycle",
		},
		StatusProjection:  "required",
		SecretSideEffects: "none",
		FinalizerPolicy:   "retain-until-confirmed-delete",
		Lifecycle: generatedruntime.LifecycleSemantics{
			ProvisioningStates: []string{},
			UpdatingStates:     []string{},
			ActiveStates:       []string{"ACTIVE", "INACTIVE"},
		},
		Delete: generatedruntime.DeleteSemantics{
			Policy:         "required",
			PendingStates:  []string{},
			TerminalStates: []string{"DELETED", "NOT_FOUND"},
		},
		List: &generatedruntime.ListSemantics{
			ResponseItemsField: "Items",
			MatchFields:        []string{"agentId", "agentType", "availabilityStatus", "compartmentId", "fleetId", "hostnameContains", "id", "lifecycleState", "timeLastSeenLessThanOrEqualTo", "timeRegisteredLessThanOrEqualTo"},
		},
		Mutation: generatedruntime.MutationSemantics{
			Mutable:       []string{"definedTags", "fleetId", "freeformTags"},
			ForceNew:      []string{"agentId", "agentType", "compartmentId"},
			ConflictsWith: map[string][]string{},
		},
		Hooks: generatedruntime.HookSet{
			Create: []generatedruntime.Hook{{Helper: "tfresource.CreateResource", EntityType: "", Action: ""}},
			Update: []generatedruntime.Hook{{Helper: "tfresource.UpdateResource", EntityType: "", Action: ""}},
			Delete: []generatedruntime.Hook{{Helper: "tfresource.DeleteResource", EntityType: "", Action: ""}},
		},
		CreateFollowUp: generatedruntime.FollowUpSemantics{
			Strategy: "read-after-write",
			Hooks:    []generatedruntime.Hook{{Helper: "tfresource.CreateResource", EntityType: "", Action: ""}},
		},
		UpdateFollowUp: generatedruntime.FollowUpSemantics{
			Strategy: "read-after-write",
			Hooks:    []generatedruntime.Hook{{Helper: "tfresource.UpdateResource", EntityType: "", Action: ""}},
		},
		DeleteFollowUp: generatedruntime.FollowUpSemantics{
			Strategy: "confirm-delete",
			Hooks:    []generatedruntime.Hook{{Helper: "tfresource.DeleteResource", EntityType: "", Action: ""}},
		},
		AuxiliaryOperations: []generatedruntime.AuxiliaryOperation{{Phase: "list", MethodName: "ListJmsPlugin", RequestTypeName: "jms.ListJmsPluginRequest", ResponseTypeName: "jms.ListJmsPluginResponse"}},
		Unsupported:         []generatedruntime.UnsupportedSemantic{},
	}
}
func newJmsPluginDefaultRuntimeHooks(sdkClient jmssdk.JavaManagementServiceClient) JmsPluginRuntimeHooks {
	return JmsPluginRuntimeHooks{
		Semantics:       newJmsPluginRuntimeSemantics(),
		Identity:        generatedruntime.IdentityHooks[*jmsv1beta1.JmsPlugin]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*jmsv1beta1.JmsPlugin]{},
		StatusHooks:     generatedruntime.StatusHooks[*jmsv1beta1.JmsPlugin]{},
		ParityHooks:     generatedruntime.ParityHooks[*jmsv1beta1.JmsPlugin]{},
		Async:           generatedruntime.AsyncHooks[*jmsv1beta1.JmsPlugin]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*jmsv1beta1.JmsPlugin]{},
		Create: runtimeOperationHooks[jmssdk.CreateJmsPluginRequest, jmssdk.CreateJmsPluginResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CreateJmsPluginDetails", RequestName: "CreateJmsPluginDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request jmssdk.CreateJmsPluginRequest) (jmssdk.CreateJmsPluginResponse, error) {
				return sdkClient.CreateJmsPlugin(ctx, request)
			},
		},
		Get: runtimeOperationHooks[jmssdk.GetJmsPluginRequest, jmssdk.GetJmsPluginResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "JmsPluginId", RequestName: "jmsPluginId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request jmssdk.GetJmsPluginRequest) (jmssdk.GetJmsPluginResponse, error) {
				return sdkClient.GetJmsPlugin(ctx, request)
			},
		},
		List: runtimeOperationHooks[jmssdk.ListJmsPluginsRequest, jmssdk.ListJmsPluginsResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "CompartmentIdInSubtree", RequestName: "compartmentIdInSubtree", Contribution: "query", PreferResourceID: false}, {FieldName: "Id", RequestName: "id", Contribution: "query", PreferResourceID: false}, {FieldName: "FleetId", RequestName: "fleetId", Contribution: "query", PreferResourceID: false}, {FieldName: "AgentId", RequestName: "agentId", Contribution: "query", PreferResourceID: false}, {FieldName: "LifecycleState", RequestName: "lifecycleState", Contribution: "query", PreferResourceID: false}, {FieldName: "AvailabilityStatus", RequestName: "availabilityStatus", Contribution: "query", PreferResourceID: false}, {FieldName: "AgentType", RequestName: "agentType", Contribution: "query", PreferResourceID: false}, {FieldName: "TimeRegisteredLessThanOrEqualTo", RequestName: "timeRegisteredLessThanOrEqualTo", Contribution: "query", PreferResourceID: false}, {FieldName: "TimeLastSeenLessThanOrEqualTo", RequestName: "timeLastSeenLessThanOrEqualTo", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}, {FieldName: "HostnameContains", RequestName: "hostnameContains", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request jmssdk.ListJmsPluginsRequest) (jmssdk.ListJmsPluginsResponse, error) {
				return sdkClient.ListJmsPlugins(ctx, request)
			},
		},
		Update: runtimeOperationHooks[jmssdk.UpdateJmsPluginRequest, jmssdk.UpdateJmsPluginResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "JmsPluginId", RequestName: "jmsPluginId", Contribution: "path", PreferResourceID: true}, {FieldName: "UpdateJmsPluginDetails", RequestName: "UpdateJmsPluginDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request jmssdk.UpdateJmsPluginRequest) (jmssdk.UpdateJmsPluginResponse, error) {
				return sdkClient.UpdateJmsPlugin(ctx, request)
			},
		},
		Delete: runtimeOperationHooks[jmssdk.DeleteJmsPluginRequest, jmssdk.DeleteJmsPluginResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "JmsPluginId", RequestName: "jmsPluginId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request jmssdk.DeleteJmsPluginRequest) (jmssdk.DeleteJmsPluginResponse, error) {
				return sdkClient.DeleteJmsPlugin(ctx, request)
			},
		},
		WrapGeneratedClient: []func(JmsPluginServiceClient) JmsPluginServiceClient{},
	}
}

func newJmsPluginRuntimeHooks(manager *JmsPluginServiceManager, sdkClient jmssdk.JavaManagementServiceClient) JmsPluginRuntimeHooks {
	hooks := newJmsPluginDefaultRuntimeHooks(sdkClient)
	for _, mutator := range jmspluginRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildJmsPluginGeneratedRuntimeConfig(
	manager *JmsPluginServiceManager,
	hooks JmsPluginRuntimeHooks,
) generatedruntime.Config[*jmsv1beta1.JmsPlugin] {
	return generatedruntime.Config[*jmsv1beta1.JmsPlugin]{
		Kind:            "JmsPlugin",
		SDKName:         "JmsPlugin",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Create: &generatedruntime.Operation{
			NewRequest: func() any { return &jmssdk.CreateJmsPluginRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Create.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Create.Call(ctx, *request.(*jmssdk.CreateJmsPluginRequest))
			},
		},
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &jmssdk.GetJmsPluginRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*jmssdk.GetJmsPluginRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &jmssdk.ListJmsPluginsRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*jmssdk.ListJmsPluginsRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &jmssdk.UpdateJmsPluginRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Update.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Update.Call(ctx, *request.(*jmssdk.UpdateJmsPluginRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &jmssdk.DeleteJmsPluginRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Delete.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Delete.Call(ctx, *request.(*jmssdk.DeleteJmsPluginRequest))
			},
		},
	}
}

func wrapJmsPluginGeneratedClient(
	hooks JmsPluginRuntimeHooks,
	delegate JmsPluginServiceClient,
) JmsPluginServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
