/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package jmsplugin

import (
	"context"
	"fmt"

	jmssdk "github.com/oracle/oci-go-sdk/v65/jms"
	jmsv1beta1 "github.com/oracle/oci-service-operator/api/jms/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// JmsPluginServiceClient is the handwritten extension seam for JmsPlugin runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*JmsPluginServiceManager).WithClient.
type JmsPluginServiceClient interface {
	CreateOrUpdate(context.Context, *jmsv1beta1.JmsPlugin, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *jmsv1beta1.JmsPlugin) (bool, error)
}

type defaultJmsPluginServiceClient struct {
	generatedruntime.ServiceClient[*jmsv1beta1.JmsPlugin]
}

var _ JmsPluginServiceClient = defaultJmsPluginServiceClient{}

var newJmsPluginServiceClient = func(manager *JmsPluginServiceManager) JmsPluginServiceClient {
	sdkClient, err := jmssdk.NewJavaManagementServiceClientWithConfigurationProvider(manager.Provider)
	hooks := newJmsPluginRuntimeHooks(manager, sdkClient)
	config := buildJmsPluginGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize JmsPlugin OCI client: %w", err)
	}
	delegate := defaultJmsPluginServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*jmsv1beta1.JmsPlugin](config),
	}
	return wrapJmsPluginGeneratedClient(hooks, delegate)
}
