/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package domaingovernance

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	tenantmanagercontrolplanev1beta1 "github.com/oracle/oci-service-operator/api/tenantmanagercontrolplane/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type DomainGovernanceServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client DomainGovernanceServiceClient
}

var _ servicemanager.OSOKServiceManager = (*DomainGovernanceServiceManager)(nil)

func NewDomainGovernanceServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *DomainGovernanceServiceManager {
	manager := &DomainGovernanceServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newDomainGovernanceServiceClient(manager)
	return manager
}

func NewDomainGovernanceServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *DomainGovernanceServiceManager {
	return NewDomainGovernanceServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *DomainGovernanceServiceManager) WithClient(client DomainGovernanceServiceClient) *DomainGovernanceServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *DomainGovernanceServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *DomainGovernanceServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *DomainGovernanceServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *DomainGovernanceServiceManager) convert(obj runtime.Object) (*tenantmanagercontrolplanev1beta1.DomainGovernance, error) {
	resource, ok := obj.(*tenantmanagercontrolplanev1beta1.DomainGovernance)
	if !ok {
		return nil, fmt.Errorf("expected *tenantmanagercontrolplanev1beta1.DomainGovernance, got %T", obj)
	}
	return resource, nil
}

func (c *DomainGovernanceServiceManager) status(resource *tenantmanagercontrolplanev1beta1.DomainGovernance) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
