/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package domaingovernance

import (
	"context"

	tenantmanagercontrolplanesdk "github.com/oracle/oci-go-sdk/v65/tenantmanagercontrolplane"
	tenantmanagercontrolplanev1beta1 "github.com/oracle/oci-service-operator/api/tenantmanagercontrolplane/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type DomainGovernanceRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *tenantmanagercontrolplanev1beta1.DomainGovernance, string) (any, error)
	BuildUpdateBody func(context.Context, *tenantmanagercontrolplanev1beta1.DomainGovernance, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*tenantmanagercontrolplanev1beta1.DomainGovernance]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*tenantmanagercontrolplanev1beta1.DomainGovernance]
	StatusHooks         generatedruntime.StatusHooks[*tenantmanagercontrolplanev1beta1.DomainGovernance]
	ParityHooks         generatedruntime.ParityHooks[*tenantmanagercontrolplanev1beta1.DomainGovernance]
	Async               generatedruntime.AsyncHooks[*tenantmanagercontrolplanev1beta1.DomainGovernance]
	DeleteHooks         generatedruntime.DeleteHooks[*tenantmanagercontrolplanev1beta1.DomainGovernance]
	Create              runtimeOperationHooks[tenantmanagercontrolplanesdk.CreateDomainGovernanceRequest, tenantmanagercontrolplanesdk.CreateDomainGovernanceResponse]
	Get                 runtimeOperationHooks[tenantmanagercontrolplanesdk.GetDomainGovernanceRequest, tenantmanagercontrolplanesdk.GetDomainGovernanceResponse]
	List                runtimeOperationHooks[tenantmanagercontrolplanesdk.ListDomainGovernancesRequest, tenantmanagercontrolplanesdk.ListDomainGovernancesResponse]
	Update              runtimeOperationHooks[tenantmanagercontrolplanesdk.UpdateDomainGovernanceRequest, tenantmanagercontrolplanesdk.UpdateDomainGovernanceResponse]
	Delete              runtimeOperationHooks[tenantmanagercontrolplanesdk.DeleteDomainGovernanceRequest, tenantmanagercontrolplanesdk.DeleteDomainGovernanceResponse]
	WrapGeneratedClient []func(DomainGovernanceServiceClient) DomainGovernanceServiceClient
}

type DomainGovernanceRuntimeHooksMutator func(*DomainGovernanceServiceManager, *DomainGovernanceRuntimeHooks)

var domaingovernanceRuntimeHooksMutators []DomainGovernanceRuntimeHooksMutator

func registerDomainGovernanceRuntimeHooksMutator(mutator DomainGovernanceRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	domaingovernanceRuntimeHooksMutators = append(domaingovernanceRuntimeHooksMutators, mutator)
}
func newDomainGovernanceRuntimeSemantics() *generatedruntime.Semantics {
	return &generatedruntime.Semantics{
		FormalService: "tenantmanagercontrolplane",
		FormalSlug:    "domaingovernance",
		Async: &generatedruntime.AsyncSemantics{
			Strategy:             "lifecycle",
			Runtime:              "generatedruntime",
			FormalClassification: "lifecycle",
		},
		StatusProjection:  "required",
		SecretSideEffects: "none",
		FinalizerPolicy:   "retain-until-confirmed-delete",
		Lifecycle: generatedruntime.LifecycleSemantics{
			ProvisioningStates: []string{"CREATING"},
			UpdatingStates:     []string{"UPDATING"},
			ActiveStates:       []string{"ACTIVE", "INACTIVE"},
		},
		Delete: generatedruntime.DeleteSemantics{
			Policy:         "required",
			PendingStates:  []string{},
			TerminalStates: []string{"NOT_FOUND"},
		},
		List: &generatedruntime.ListSemantics{
			ResponseItemsField: "Items",
			MatchFields:        []string{"compartmentId", "domainId"},
		},
		Mutation: generatedruntime.MutationSemantics{
			Mutable:       []string{"definedTags", "freeformTags", "isGovernanceEnabled", "subscriptionEmail"},
			ForceNew:      []string{"compartmentId", "domainId", "onsSubscriptionId", "onsTopicId"},
			ConflictsWith: map[string][]string{},
		},
		Hooks: generatedruntime.HookSet{
			Create: []generatedruntime.Hook{{Helper: "tfresource.CreateResource", EntityType: "", Action: ""}},
			Update: []generatedruntime.Hook{{Helper: "tfresource.UpdateResource", EntityType: "", Action: ""}},
			Delete: []generatedruntime.Hook{{Helper: "tfresource.DeleteResource", EntityType: "", Action: ""}},
		},
		CreateFollowUp: generatedruntime.FollowUpSemantics{
			Strategy: "none",
			Hooks:    []generatedruntime.Hook{{Helper: "tfresource.CreateResource", EntityType: "", Action: ""}},
		},
		UpdateFollowUp: generatedruntime.FollowUpSemantics{
			Strategy: "none",
			Hooks:    []generatedruntime.Hook{{Helper: "tfresource.UpdateResource", EntityType: "", Action: ""}},
		},
		DeleteFollowUp: generatedruntime.FollowUpSemantics{
			Strategy: "GetDomainGovernance/ListDomainGovernances confirm-delete until NOT_FOUND",
			Hooks:    []generatedruntime.Hook{{Helper: "tfresource.DeleteResource", EntityType: "", Action: ""}},
		},
		AuxiliaryOperations: []generatedruntime.AuxiliaryOperation{},
		Unsupported:         []generatedruntime.UnsupportedSemantic{},
	}
}
func newDomainGovernanceDefaultRuntimeHooks(sdkClient tenantmanagercontrolplanesdk.DomainGovernanceClient) DomainGovernanceRuntimeHooks {
	return DomainGovernanceRuntimeHooks{
		Semantics:       newDomainGovernanceRuntimeSemantics(),
		Identity:        generatedruntime.IdentityHooks[*tenantmanagercontrolplanev1beta1.DomainGovernance]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*tenantmanagercontrolplanev1beta1.DomainGovernance]{},
		StatusHooks:     generatedruntime.StatusHooks[*tenantmanagercontrolplanev1beta1.DomainGovernance]{},
		ParityHooks:     generatedruntime.ParityHooks[*tenantmanagercontrolplanev1beta1.DomainGovernance]{},
		Async:           generatedruntime.AsyncHooks[*tenantmanagercontrolplanev1beta1.DomainGovernance]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*tenantmanagercontrolplanev1beta1.DomainGovernance]{},
		Create: runtimeOperationHooks[tenantmanagercontrolplanesdk.CreateDomainGovernanceRequest, tenantmanagercontrolplanesdk.CreateDomainGovernanceResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CreateDomainGovernanceDetails", RequestName: "CreateDomainGovernanceDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request tenantmanagercontrolplanesdk.CreateDomainGovernanceRequest) (tenantmanagercontrolplanesdk.CreateDomainGovernanceResponse, error) {
				return sdkClient.CreateDomainGovernance(ctx, request)
			},
		},
		Get: runtimeOperationHooks[tenantmanagercontrolplanesdk.GetDomainGovernanceRequest, tenantmanagercontrolplanesdk.GetDomainGovernanceResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "DomainGovernanceId", RequestName: "domainGovernanceId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request tenantmanagercontrolplanesdk.GetDomainGovernanceRequest) (tenantmanagercontrolplanesdk.GetDomainGovernanceResponse, error) {
				return sdkClient.GetDomainGovernance(ctx, request)
			},
		},
		List: runtimeOperationHooks[tenantmanagercontrolplanesdk.ListDomainGovernancesRequest, tenantmanagercontrolplanesdk.ListDomainGovernancesResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "DomainId", RequestName: "domainId", Contribution: "query", PreferResourceID: false}, {FieldName: "DomainGovernanceId", RequestName: "domainGovernanceId", Contribution: "query", PreferResourceID: false}, {FieldName: "LifecycleState", RequestName: "lifecycleState", Contribution: "query", PreferResourceID: false}, {FieldName: "Name", RequestName: "name", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request tenantmanagercontrolplanesdk.ListDomainGovernancesRequest) (tenantmanagercontrolplanesdk.ListDomainGovernancesResponse, error) {
				return sdkClient.ListDomainGovernances(ctx, request)
			},
		},
		Update: runtimeOperationHooks[tenantmanagercontrolplanesdk.UpdateDomainGovernanceRequest, tenantmanagercontrolplanesdk.UpdateDomainGovernanceResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "DomainGovernanceId", RequestName: "domainGovernanceId", Contribution: "path", PreferResourceID: true}, {FieldName: "UpdateDomainGovernanceDetails", RequestName: "UpdateDomainGovernanceDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request tenantmanagercontrolplanesdk.UpdateDomainGovernanceRequest) (tenantmanagercontrolplanesdk.UpdateDomainGovernanceResponse, error) {
				return sdkClient.UpdateDomainGovernance(ctx, request)
			},
		},
		Delete: runtimeOperationHooks[tenantmanagercontrolplanesdk.DeleteDomainGovernanceRequest, tenantmanagercontrolplanesdk.DeleteDomainGovernanceResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "DomainGovernanceId", RequestName: "domainGovernanceId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request tenantmanagercontrolplanesdk.DeleteDomainGovernanceRequest) (tenantmanagercontrolplanesdk.DeleteDomainGovernanceResponse, error) {
				return sdkClient.DeleteDomainGovernance(ctx, request)
			},
		},
		WrapGeneratedClient: []func(DomainGovernanceServiceClient) DomainGovernanceServiceClient{},
	}
}

func newDomainGovernanceRuntimeHooks(manager *DomainGovernanceServiceManager, sdkClient tenantmanagercontrolplanesdk.DomainGovernanceClient) DomainGovernanceRuntimeHooks {
	hooks := newDomainGovernanceDefaultRuntimeHooks(sdkClient)
	for _, mutator := range domaingovernanceRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildDomainGovernanceGeneratedRuntimeConfig(
	manager *DomainGovernanceServiceManager,
	hooks DomainGovernanceRuntimeHooks,
) generatedruntime.Config[*tenantmanagercontrolplanev1beta1.DomainGovernance] {
	return generatedruntime.Config[*tenantmanagercontrolplanev1beta1.DomainGovernance]{
		Kind:            "DomainGovernance",
		SDKName:         "DomainGovernance",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Create: &generatedruntime.Operation{
			NewRequest: func() any { return &tenantmanagercontrolplanesdk.CreateDomainGovernanceRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Create.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Create.Call(ctx, *request.(*tenantmanagercontrolplanesdk.CreateDomainGovernanceRequest))
			},
		},
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &tenantmanagercontrolplanesdk.GetDomainGovernanceRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*tenantmanagercontrolplanesdk.GetDomainGovernanceRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &tenantmanagercontrolplanesdk.ListDomainGovernancesRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*tenantmanagercontrolplanesdk.ListDomainGovernancesRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &tenantmanagercontrolplanesdk.UpdateDomainGovernanceRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Update.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Update.Call(ctx, *request.(*tenantmanagercontrolplanesdk.UpdateDomainGovernanceRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &tenantmanagercontrolplanesdk.DeleteDomainGovernanceRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Delete.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Delete.Call(ctx, *request.(*tenantmanagercontrolplanesdk.DeleteDomainGovernanceRequest))
			},
		},
	}
}

func wrapDomainGovernanceGeneratedClient(
	hooks DomainGovernanceRuntimeHooks,
	delegate DomainGovernanceServiceClient,
) DomainGovernanceServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
