/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package domaingovernance

import (
	"context"
	"fmt"

	tenantmanagercontrolplanesdk "github.com/oracle/oci-go-sdk/v65/tenantmanagercontrolplane"
	tenantmanagercontrolplanev1beta1 "github.com/oracle/oci-service-operator/api/tenantmanagercontrolplane/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DomainGovernanceServiceClient is the handwritten extension seam for DomainGovernance runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*DomainGovernanceServiceManager).WithClient.
type DomainGovernanceServiceClient interface {
	CreateOrUpdate(context.Context, *tenantmanagercontrolplanev1beta1.DomainGovernance, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *tenantmanagercontrolplanev1beta1.DomainGovernance) (bool, error)
}

type defaultDomainGovernanceServiceClient struct {
	generatedruntime.ServiceClient[*tenantmanagercontrolplanev1beta1.DomainGovernance]
}

var _ DomainGovernanceServiceClient = defaultDomainGovernanceServiceClient{}

var newDomainGovernanceServiceClient = func(manager *DomainGovernanceServiceManager) DomainGovernanceServiceClient {
	sdkClient, err := tenantmanagercontrolplanesdk.NewDomainGovernanceClientWithConfigurationProvider(manager.Provider)
	hooks := newDomainGovernanceRuntimeHooks(manager, sdkClient)
	config := buildDomainGovernanceGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize DomainGovernance OCI client: %w", err)
	}
	delegate := defaultDomainGovernanceServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*tenantmanagercontrolplanev1beta1.DomainGovernance](config),
	}
	return wrapDomainGovernanceGeneratedClient(hooks, delegate)
}
