/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DataSourceSpec defines the desired state of DataSource.
type DataSourceSpec struct {
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the parent KnowledgeBase.
	// +kubebuilder:validation:Required
	KnowledgeBaseId string `json:"knowledgeBaseId"`
	// +kubebuilder:validation:Required
	DataSourceConfig DataSourceConfig `json:"dataSourceConfig"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment to create the data source in.
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// A user-friendly name. Does not have to be unique, and it's changeable. Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	DisplayName string `json:"displayName,omitempty"`
	// A description of the data source.
	// +kubebuilder:validation:Optional
	Description string `json:"description,omitempty"`
	// Key-value pairs to allow additional configurations.
	// +kubebuilder:validation:Optional
	Metadata map[string]string `json:"metadata,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	// +kubebuilder:validation:Optional
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
}

// DataSourceConfigObjectStoragePrefix defines nested fields for DataSource.DataSourceConfig.ObjectStoragePrefix.
type DataSourceConfigObjectStoragePrefix struct {
	// The namespace name of an object.
	// +kubebuilder:validation:Required
	NamespaceName string `json:"namespaceName"`
	// The bucket name of an object.
	// +kubebuilder:validation:Required
	BucketName string `json:"bucketName"`
	// The prefix of file object(s) or folder prefix.
	// +kubebuilder:validation:Optional
	Prefix string `json:"prefix,omitempty"`
}

// DataSourceConfig defines nested fields for DataSource.DataSourceConfig.
type DataSourceConfig struct {
	// +kubebuilder:validation:Optional
	JsonData string `json:"jsonData,omitempty"`
	// Flag to enable or disable multi modality such as image processing while ingestion of data. True enable the processing and false exclude the multi modality contents during ingestion.
	// +kubebuilder:validation:Optional
	ShouldEnableMultiModality bool `json:"shouldEnableMultiModality,omitempty"`
	// +kubebuilder:validation:Optional
	DataSourceConfigType string `json:"dataSourceConfigType,omitempty"`
	// The locations of data items in Object Storage, can either be an object (File) or a prefix (folder).
	// +kubebuilder:validation:Optional
	ObjectStoragePrefixes []DataSourceConfigObjectStoragePrefix `json:"objectStoragePrefixes,omitempty"`
}

// DataSourceStatus defines the observed state of DataSource.
type DataSourceStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the data source.
	Id string `json:"id,omitempty"`
	// A user-friendly name. Does not have to be unique, and it's changeable.
	DisplayName string `json:"displayName,omitempty"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartment.
	CompartmentId string `json:"compartmentId,omitempty"`
	// The OCID (https://docs.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the parent KnowledgeBase.
	KnowledgeBaseId  string           `json:"knowledgeBaseId,omitempty"`
	DataSourceConfig DataSourceConfig `json:"dataSourceConfig,omitempty"`
	// The date and time the data source was created, in the format defined by RFC 3339 (https://tools.ietf.org/html/rfc3339).
	// Example: `2016-08-25T21:10:29.600Z`
	TimeCreated string `json:"timeCreated,omitempty"`
	// The current state of the data source.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Department": "Finance"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// For more information, see Resource Tags (https://docs.oracle.com/iaas/Content/General/Concepts/resourcetags.htm).
	// Example: `{"Operations": {"CostCenter": "42"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// A description of the data source.
	Description string `json:"description,omitempty"`
	// Key-value pairs to allow additional configurations.
	Metadata map[string]string `json:"metadata,omitempty"`
	// The date and time the data source was updated, in the format defined by RFC 3339 (https://tools.ietf.org/html/rfc3339).
	// Example: `2016-08-25T21:10:29.600Z`
	TimeUpdated string `json:"timeUpdated,omitempty"`
	// A message that describes the current state of the data source in more detail. For example,
	// can be used to provide actionable information for a resource in the Failed state.
	LifecycleDetails string `json:"lifecycleDetails,omitempty"`
	// System tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"orcl-cloud": {"free-tier-retained": "true"}}`
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="DisplayName",type="string",JSONPath=".spec.displayName",priority=1
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the DataSource",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the DataSource",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// DataSource is the Schema for the datasources API.
type DataSource struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DataSourceSpec   `json:"spec,omitempty"`
	Status DataSourceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// DataSourceList contains a list of DataSource.
type DataSourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DataSource `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DataSource{}, &DataSourceList{})
}
