//go:build !ignore_autogenerated

/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/oracle/oci-service-operator/pkg/shared"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Agent) DeepCopyInto(out *Agent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Agent.
func (in *Agent) DeepCopy() *Agent {
	if in == nil {
		return nil
	}
	out := new(Agent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Agent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpoint) DeepCopyInto(out *AgentEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpoint.
func (in *AgentEndpoint) DeepCopy() *AgentEndpoint {
	if in == nil {
		return nil
	}
	out := new(AgentEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointContentModerationConfig) DeepCopyInto(out *AgentEndpointContentModerationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointContentModerationConfig.
func (in *AgentEndpointContentModerationConfig) DeepCopy() *AgentEndpointContentModerationConfig {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointContentModerationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointGuardrailConfig) DeepCopyInto(out *AgentEndpointGuardrailConfig) {
	*out = *in
	out.ContentModerationConfig = in.ContentModerationConfig
	out.PromptInjectionConfig = in.PromptInjectionConfig
	out.PersonallyIdentifiableInformationConfig = in.PersonallyIdentifiableInformationConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointGuardrailConfig.
func (in *AgentEndpointGuardrailConfig) DeepCopy() *AgentEndpointGuardrailConfig {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointGuardrailConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointGuardrailConfigContentModerationConfig) DeepCopyInto(out *AgentEndpointGuardrailConfigContentModerationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointGuardrailConfigContentModerationConfig.
func (in *AgentEndpointGuardrailConfigContentModerationConfig) DeepCopy() *AgentEndpointGuardrailConfigContentModerationConfig {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointGuardrailConfigContentModerationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointGuardrailConfigPersonallyIdentifiableInformationConfig) DeepCopyInto(out *AgentEndpointGuardrailConfigPersonallyIdentifiableInformationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointGuardrailConfigPersonallyIdentifiableInformationConfig.
func (in *AgentEndpointGuardrailConfigPersonallyIdentifiableInformationConfig) DeepCopy() *AgentEndpointGuardrailConfigPersonallyIdentifiableInformationConfig {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointGuardrailConfigPersonallyIdentifiableInformationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointGuardrailConfigPromptInjectionConfig) DeepCopyInto(out *AgentEndpointGuardrailConfigPromptInjectionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointGuardrailConfigPromptInjectionConfig.
func (in *AgentEndpointGuardrailConfigPromptInjectionConfig) DeepCopy() *AgentEndpointGuardrailConfigPromptInjectionConfig {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointGuardrailConfigPromptInjectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointHumanInputConfig) DeepCopyInto(out *AgentEndpointHumanInputConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointHumanInputConfig.
func (in *AgentEndpointHumanInputConfig) DeepCopy() *AgentEndpointHumanInputConfig {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointHumanInputConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointList) DeepCopyInto(out *AgentEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointList.
func (in *AgentEndpointList) DeepCopy() *AgentEndpointList {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointOutputConfig) DeepCopyInto(out *AgentEndpointOutputConfig) {
	*out = *in
	out.OutputLocation = in.OutputLocation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointOutputConfig.
func (in *AgentEndpointOutputConfig) DeepCopy() *AgentEndpointOutputConfig {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointOutputConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointOutputConfigOutputLocation) DeepCopyInto(out *AgentEndpointOutputConfigOutputLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointOutputConfigOutputLocation.
func (in *AgentEndpointOutputConfigOutputLocation) DeepCopy() *AgentEndpointOutputConfigOutputLocation {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointOutputConfigOutputLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointProvisionedCapacityConfig) DeepCopyInto(out *AgentEndpointProvisionedCapacityConfig) {
	*out = *in
	out.PlatformRuntimeConfig = in.PlatformRuntimeConfig
	if in.ToolRuntimeConfigs != nil {
		in, out := &in.ToolRuntimeConfigs, &out.ToolRuntimeConfigs
		*out = make([]AgentEndpointProvisionedCapacityConfigToolRuntimeConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointProvisionedCapacityConfig.
func (in *AgentEndpointProvisionedCapacityConfig) DeepCopy() *AgentEndpointProvisionedCapacityConfig {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointProvisionedCapacityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointProvisionedCapacityConfigPlatformRuntimeConfig) DeepCopyInto(out *AgentEndpointProvisionedCapacityConfigPlatformRuntimeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointProvisionedCapacityConfigPlatformRuntimeConfig.
func (in *AgentEndpointProvisionedCapacityConfigPlatformRuntimeConfig) DeepCopy() *AgentEndpointProvisionedCapacityConfigPlatformRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointProvisionedCapacityConfigPlatformRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointProvisionedCapacityConfigToolRuntimeConfig) DeepCopyInto(out *AgentEndpointProvisionedCapacityConfigToolRuntimeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointProvisionedCapacityConfigToolRuntimeConfig.
func (in *AgentEndpointProvisionedCapacityConfigToolRuntimeConfig) DeepCopy() *AgentEndpointProvisionedCapacityConfigToolRuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointProvisionedCapacityConfigToolRuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointSessionConfig) DeepCopyInto(out *AgentEndpointSessionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointSessionConfig.
func (in *AgentEndpointSessionConfig) DeepCopy() *AgentEndpointSessionConfig {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointSessionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointSpec) DeepCopyInto(out *AgentEndpointSpec) {
	*out = *in
	out.ContentModerationConfig = in.ContentModerationConfig
	out.GuardrailConfig = in.GuardrailConfig
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.HumanInputConfig = in.HumanInputConfig
	out.OutputConfig = in.OutputConfig
	out.SessionConfig = in.SessionConfig
	in.ProvisionedCapacityConfig.DeepCopyInto(&out.ProvisionedCapacityConfig)
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointSpec.
func (in *AgentEndpointSpec) DeepCopy() *AgentEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentEndpointStatus) DeepCopyInto(out *AgentEndpointStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	out.ContentModerationConfig = in.ContentModerationConfig
	out.GuardrailConfig = in.GuardrailConfig
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.HumanInputConfig = in.HumanInputConfig
	out.OutputConfig = in.OutputConfig
	out.SessionConfig = in.SessionConfig
	in.ProvisionedCapacityConfig.DeepCopyInto(&out.ProvisionedCapacityConfig)
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentEndpointStatus.
func (in *AgentEndpointStatus) DeepCopy() *AgentEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(AgentEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentList) DeepCopyInto(out *AgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Agent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentList.
func (in *AgentList) DeepCopy() *AgentList {
	if in == nil {
		return nil
	}
	out := new(AgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLlmConfig) DeepCopyInto(out *AgentLlmConfig) {
	*out = *in
	in.RoutingLlmCustomization.DeepCopyInto(&out.RoutingLlmCustomization)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLlmConfig.
func (in *AgentLlmConfig) DeepCopy() *AgentLlmConfig {
	if in == nil {
		return nil
	}
	out := new(AgentLlmConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLlmConfigRoutingLlmCustomization) DeepCopyInto(out *AgentLlmConfigRoutingLlmCustomization) {
	*out = *in
	out.LlmSelection = in.LlmSelection
	if in.LlmHyperParameters != nil {
		in, out := &in.LlmHyperParameters, &out.LlmHyperParameters
		*out = make(map[string]shared.JSONValue, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLlmConfigRoutingLlmCustomization.
func (in *AgentLlmConfigRoutingLlmCustomization) DeepCopy() *AgentLlmConfigRoutingLlmCustomization {
	if in == nil {
		return nil
	}
	out := new(AgentLlmConfigRoutingLlmCustomization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentLlmConfigRoutingLlmCustomizationLlmSelection) DeepCopyInto(out *AgentLlmConfigRoutingLlmCustomizationLlmSelection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentLlmConfigRoutingLlmCustomizationLlmSelection.
func (in *AgentLlmConfigRoutingLlmCustomizationLlmSelection) DeepCopy() *AgentLlmConfigRoutingLlmCustomizationLlmSelection {
	if in == nil {
		return nil
	}
	out := new(AgentLlmConfigRoutingLlmCustomizationLlmSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.KnowledgeBaseIds != nil {
		in, out := &in.KnowledgeBaseIds, &out.KnowledgeBaseIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.LlmConfig.DeepCopyInto(&out.LlmConfig)
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSpec.
func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentStatus) DeepCopyInto(out *AgentStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	if in.KnowledgeBaseIds != nil {
		in, out := &in.KnowledgeBaseIds, &out.KnowledgeBaseIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.LlmConfig.DeepCopyInto(&out.LlmConfig)
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentStatus.
func (in *AgentStatus) DeepCopy() *AgentStatus {
	if in == nil {
		return nil
	}
	out := new(AgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSource) DeepCopyInto(out *DataSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSource.
func (in *DataSource) DeepCopy() *DataSource {
	if in == nil {
		return nil
	}
	out := new(DataSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceConfig) DeepCopyInto(out *DataSourceConfig) {
	*out = *in
	if in.ObjectStoragePrefixes != nil {
		in, out := &in.ObjectStoragePrefixes, &out.ObjectStoragePrefixes
		*out = make([]DataSourceConfigObjectStoragePrefix, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceConfig.
func (in *DataSourceConfig) DeepCopy() *DataSourceConfig {
	if in == nil {
		return nil
	}
	out := new(DataSourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceConfigObjectStoragePrefix) DeepCopyInto(out *DataSourceConfigObjectStoragePrefix) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceConfigObjectStoragePrefix.
func (in *DataSourceConfigObjectStoragePrefix) DeepCopy() *DataSourceConfigObjectStoragePrefix {
	if in == nil {
		return nil
	}
	out := new(DataSourceConfigObjectStoragePrefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceList) DeepCopyInto(out *DataSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DataSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceList.
func (in *DataSourceList) DeepCopy() *DataSourceList {
	if in == nil {
		return nil
	}
	out := new(DataSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DataSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSpec) DeepCopyInto(out *DataSourceSpec) {
	*out = *in
	in.DataSourceConfig.DeepCopyInto(&out.DataSourceConfig)
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpec.
func (in *DataSourceSpec) DeepCopy() *DataSourceSpec {
	if in == nil {
		return nil
	}
	out := new(DataSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceStatus) DeepCopyInto(out *DataSourceStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	in.DataSourceConfig.DeepCopyInto(&out.DataSourceConfig)
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceStatus.
func (in *DataSourceStatus) DeepCopy() *DataSourceStatus {
	if in == nil {
		return nil
	}
	out := new(DataSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBase) DeepCopyInto(out *KnowledgeBase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBase.
func (in *KnowledgeBase) DeepCopy() *KnowledgeBase {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnowledgeBase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseIndexConfig) DeepCopyInto(out *KnowledgeBaseIndexConfig) {
	*out = *in
	out.DatabaseConnection = in.DatabaseConnection
	if in.DatabaseFunctions != nil {
		in, out := &in.DatabaseFunctions, &out.DatabaseFunctions
		*out = make([]KnowledgeBaseIndexConfigDatabaseFunction, len(*in))
		copy(*out, *in)
	}
	out.SecretDetail = in.SecretDetail
	if in.Indexes != nil {
		in, out := &in.Indexes, &out.Indexes
		*out = make([]KnowledgeBaseIndexConfigIndex, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseIndexConfig.
func (in *KnowledgeBaseIndexConfig) DeepCopy() *KnowledgeBaseIndexConfig {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseIndexConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseIndexConfigDatabaseConnection) DeepCopyInto(out *KnowledgeBaseIndexConfigDatabaseConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseIndexConfigDatabaseConnection.
func (in *KnowledgeBaseIndexConfigDatabaseConnection) DeepCopy() *KnowledgeBaseIndexConfigDatabaseConnection {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseIndexConfigDatabaseConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseIndexConfigDatabaseFunction) DeepCopyInto(out *KnowledgeBaseIndexConfigDatabaseFunction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseIndexConfigDatabaseFunction.
func (in *KnowledgeBaseIndexConfigDatabaseFunction) DeepCopy() *KnowledgeBaseIndexConfigDatabaseFunction {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseIndexConfigDatabaseFunction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseIndexConfigIndex) DeepCopyInto(out *KnowledgeBaseIndexConfigIndex) {
	*out = *in
	out.Schema = in.Schema
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseIndexConfigIndex.
func (in *KnowledgeBaseIndexConfigIndex) DeepCopy() *KnowledgeBaseIndexConfigIndex {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseIndexConfigIndex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseIndexConfigIndexSchema) DeepCopyInto(out *KnowledgeBaseIndexConfigIndexSchema) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseIndexConfigIndexSchema.
func (in *KnowledgeBaseIndexConfigIndexSchema) DeepCopy() *KnowledgeBaseIndexConfigIndexSchema {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseIndexConfigIndexSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseIndexConfigSecretDetail) DeepCopyInto(out *KnowledgeBaseIndexConfigSecretDetail) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseIndexConfigSecretDetail.
func (in *KnowledgeBaseIndexConfigSecretDetail) DeepCopy() *KnowledgeBaseIndexConfigSecretDetail {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseIndexConfigSecretDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseList) DeepCopyInto(out *KnowledgeBaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KnowledgeBase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseList.
func (in *KnowledgeBaseList) DeepCopy() *KnowledgeBaseList {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnowledgeBaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseSpec) DeepCopyInto(out *KnowledgeBaseSpec) {
	*out = *in
	in.IndexConfig.DeepCopyInto(&out.IndexConfig)
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseSpec.
func (in *KnowledgeBaseSpec) DeepCopy() *KnowledgeBaseSpec {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseStatistics) DeepCopyInto(out *KnowledgeBaseStatistics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseStatistics.
func (in *KnowledgeBaseStatistics) DeepCopy() *KnowledgeBaseStatistics {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseStatistics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseStatus) DeepCopyInto(out *KnowledgeBaseStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	in.IndexConfig.DeepCopyInto(&out.IndexConfig)
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	out.KnowledgeBaseStatistics = in.KnowledgeBaseStatistics
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseStatus.
func (in *KnowledgeBaseStatus) DeepCopy() *KnowledgeBaseStatus {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseStatus)
	in.DeepCopyInto(out)
	return out
}
