#
# Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: budget.oracle.com/v1beta1
kind: Budget
metadata:
  name: osok-budget-${OSOK_E2E_SUFFIX}
spec:
  compartmentId: ${OCI_COMPARTMENT_ID}
  amount: 100
  resetPeriod: MONTHLY
  displayName: osok-budget-${OSOK_E2E_SUFFIX}
  targetType: COMPARTMENT
  targets:
    - ${OCI_COMPARTMENT_ID}
