---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - mediaservices.oracle.com
  resources:
  - mediaassets
  - mediaworkflowconfigurations
  - mediaworkflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mediaservices.oracle.com
  resources:
  - mediaassets/finalizers
  - mediaworkflowconfigurations/finalizers
  - mediaworkflows/finalizers
  verbs:
  - update
- apiGroups:
  - mediaservices.oracle.com
  resources:
  - mediaassets/status
  - mediaworkflowconfigurations/status
  - mediaworkflows/status
  verbs:
  - get
  - patch
  - update
