---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - opensearch.oracle.com
  resources:
  - opensearchopensearchclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.oracle.com
  resources:
  - opensearchopensearchclusters/finalizers
  verbs:
  - update
- apiGroups:
  - opensearch.oracle.com
  resources:
  - opensearchopensearchclusters/status
  verbs:
  - get
  - patch
  - update
