//go:build !ignore_autogenerated

/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/oracle/oci-service-operator/pkg/shared"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabase) DeepCopyInto(out *DistributedDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabase.
func (in *DistributedDatabase) DeepCopy() *DistributedDatabase {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributedDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseCatalogDetail) DeepCopyInto(out *DistributedDatabaseCatalogDetail) {
	*out = *in
	out.DbStorageVaultDetails = in.DbStorageVaultDetails
	in.VmClusterDetails.DeepCopyInto(&out.VmClusterDetails)
	if in.PeerDetails != nil {
		in, out := &in.PeerDetails, &out.PeerDetails
		*out = make([]DistributedDatabaseCatalogDetailPeerDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PeerVmClusterIds != nil {
		in, out := &in.PeerVmClusterIds, &out.PeerVmClusterIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseCatalogDetail.
func (in *DistributedDatabaseCatalogDetail) DeepCopy() *DistributedDatabaseCatalogDetail {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseCatalogDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseCatalogDetailDbStorageVaultDetails) DeepCopyInto(out *DistributedDatabaseCatalogDetailDbStorageVaultDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseCatalogDetailDbStorageVaultDetails.
func (in *DistributedDatabaseCatalogDetailDbStorageVaultDetails) DeepCopy() *DistributedDatabaseCatalogDetailDbStorageVaultDetails {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseCatalogDetailDbStorageVaultDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseCatalogDetailMetadata) DeepCopyInto(out *DistributedDatabaseCatalogDetailMetadata) {
	*out = *in
	if in.PropertiesMap != nil {
		in, out := &in.PropertiesMap, &out.PropertiesMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseCatalogDetailMetadata.
func (in *DistributedDatabaseCatalogDetailMetadata) DeepCopy() *DistributedDatabaseCatalogDetailMetadata {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseCatalogDetailMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseCatalogDetailPeerDetail) DeepCopyInto(out *DistributedDatabaseCatalogDetailPeerDetail) {
	*out = *in
	out.DbStorageVaultDetails = in.DbStorageVaultDetails
	in.VmClusterDetails.DeepCopyInto(&out.VmClusterDetails)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseCatalogDetailPeerDetail.
func (in *DistributedDatabaseCatalogDetailPeerDetail) DeepCopy() *DistributedDatabaseCatalogDetailPeerDetail {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseCatalogDetailPeerDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseCatalogDetailPeerDetailDbStorageVaultDetails) DeepCopyInto(out *DistributedDatabaseCatalogDetailPeerDetailDbStorageVaultDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseCatalogDetailPeerDetailDbStorageVaultDetails.
func (in *DistributedDatabaseCatalogDetailPeerDetailDbStorageVaultDetails) DeepCopy() *DistributedDatabaseCatalogDetailPeerDetailDbStorageVaultDetails {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseCatalogDetailPeerDetailDbStorageVaultDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseCatalogDetailPeerDetailMetadata) DeepCopyInto(out *DistributedDatabaseCatalogDetailPeerDetailMetadata) {
	*out = *in
	if in.PropertiesMap != nil {
		in, out := &in.PropertiesMap, &out.PropertiesMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseCatalogDetailPeerDetailMetadata.
func (in *DistributedDatabaseCatalogDetailPeerDetailMetadata) DeepCopy() *DistributedDatabaseCatalogDetailPeerDetailMetadata {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseCatalogDetailPeerDetailMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseCatalogDetailPeerDetailVmClusterDetails) DeepCopyInto(out *DistributedDatabaseCatalogDetailPeerDetailVmClusterDetails) {
	*out = *in
	if in.SshPublicKeys != nil {
		in, out := &in.SshPublicKeys, &out.SshPublicKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NsgIds != nil {
		in, out := &in.NsgIds, &out.NsgIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BackupNetworkNsgIds != nil {
		in, out := &in.BackupNetworkNsgIds, &out.BackupNetworkNsgIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseCatalogDetailPeerDetailVmClusterDetails.
func (in *DistributedDatabaseCatalogDetailPeerDetailVmClusterDetails) DeepCopy() *DistributedDatabaseCatalogDetailPeerDetailVmClusterDetails {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseCatalogDetailPeerDetailVmClusterDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseCatalogDetailVmClusterDetails) DeepCopyInto(out *DistributedDatabaseCatalogDetailVmClusterDetails) {
	*out = *in
	if in.SshPublicKeys != nil {
		in, out := &in.SshPublicKeys, &out.SshPublicKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NsgIds != nil {
		in, out := &in.NsgIds, &out.NsgIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BackupNetworkNsgIds != nil {
		in, out := &in.BackupNetworkNsgIds, &out.BackupNetworkNsgIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseCatalogDetailVmClusterDetails.
func (in *DistributedDatabaseCatalogDetailVmClusterDetails) DeepCopy() *DistributedDatabaseCatalogDetailVmClusterDetails {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseCatalogDetailVmClusterDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseConnectionStrings) DeepCopyInto(out *DistributedDatabaseConnectionStrings) {
	*out = *in
	if in.AllConnectionStrings != nil {
		in, out := &in.AllConnectionStrings, &out.AllConnectionStrings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseConnectionStrings.
func (in *DistributedDatabaseConnectionStrings) DeepCopy() *DistributedDatabaseConnectionStrings {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseConnectionStrings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseDbBackupConfig) DeepCopyInto(out *DistributedDatabaseDbBackupConfig) {
	*out = *in
	if in.BackupDestinationDetails != nil {
		in, out := &in.BackupDestinationDetails, &out.BackupDestinationDetails
		*out = make([]DistributedDatabaseDbBackupConfigBackupDestinationDetail, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseDbBackupConfig.
func (in *DistributedDatabaseDbBackupConfig) DeepCopy() *DistributedDatabaseDbBackupConfig {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseDbBackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseDbBackupConfigBackupDestinationDetail) DeepCopyInto(out *DistributedDatabaseDbBackupConfigBackupDestinationDetail) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseDbBackupConfigBackupDestinationDetail.
func (in *DistributedDatabaseDbBackupConfigBackupDestinationDetail) DeepCopy() *DistributedDatabaseDbBackupConfigBackupDestinationDetail {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseDbBackupConfigBackupDestinationDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseGsmDetail) DeepCopyInto(out *DistributedDatabaseGsmDetail) {
	*out = *in
	out.GsmImageDetails = in.GsmImageDetails
	in.Metadata.DeepCopyInto(&out.Metadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseGsmDetail.
func (in *DistributedDatabaseGsmDetail) DeepCopy() *DistributedDatabaseGsmDetail {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseGsmDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseGsmDetailGsmImageDetails) DeepCopyInto(out *DistributedDatabaseGsmDetailGsmImageDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseGsmDetailGsmImageDetails.
func (in *DistributedDatabaseGsmDetailGsmImageDetails) DeepCopy() *DistributedDatabaseGsmDetailGsmImageDetails {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseGsmDetailGsmImageDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseGsmDetailMetadata) DeepCopyInto(out *DistributedDatabaseGsmDetailMetadata) {
	*out = *in
	if in.PropertiesMap != nil {
		in, out := &in.PropertiesMap, &out.PropertiesMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseGsmDetailMetadata.
func (in *DistributedDatabaseGsmDetailMetadata) DeepCopy() *DistributedDatabaseGsmDetailMetadata {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseGsmDetailMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseLatestGsmImageDetails) DeepCopyInto(out *DistributedDatabaseLatestGsmImageDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseLatestGsmImageDetails.
func (in *DistributedDatabaseLatestGsmImageDetails) DeepCopy() *DistributedDatabaseLatestGsmImageDetails {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseLatestGsmImageDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseList) DeepCopyInto(out *DistributedDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DistributedDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseList.
func (in *DistributedDatabaseList) DeepCopy() *DistributedDatabaseList {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributedDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseMetadata) DeepCopyInto(out *DistributedDatabaseMetadata) {
	*out = *in
	if in.PropertiesMap != nil {
		in, out := &in.PropertiesMap, &out.PropertiesMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseMetadata.
func (in *DistributedDatabaseMetadata) DeepCopy() *DistributedDatabaseMetadata {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabasePrivateEndpoint) DeepCopyInto(out *DistributedDatabasePrivateEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabasePrivateEndpoint.
func (in *DistributedDatabasePrivateEndpoint) DeepCopy() *DistributedDatabasePrivateEndpoint {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabasePrivateEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributedDatabasePrivateEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabasePrivateEndpointGloballyDistributedAutonomousDatabase) DeepCopyInto(out *DistributedDatabasePrivateEndpointGloballyDistributedAutonomousDatabase) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabasePrivateEndpointGloballyDistributedAutonomousDatabase.
func (in *DistributedDatabasePrivateEndpointGloballyDistributedAutonomousDatabase) DeepCopy() *DistributedDatabasePrivateEndpointGloballyDistributedAutonomousDatabase {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabasePrivateEndpointGloballyDistributedAutonomousDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabasePrivateEndpointGloballyDistributedDatabase) DeepCopyInto(out *DistributedDatabasePrivateEndpointGloballyDistributedDatabase) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabasePrivateEndpointGloballyDistributedDatabase.
func (in *DistributedDatabasePrivateEndpointGloballyDistributedDatabase) DeepCopy() *DistributedDatabasePrivateEndpointGloballyDistributedDatabase {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabasePrivateEndpointGloballyDistributedDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabasePrivateEndpointList) DeepCopyInto(out *DistributedDatabasePrivateEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DistributedDatabasePrivateEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabasePrivateEndpointList.
func (in *DistributedDatabasePrivateEndpointList) DeepCopy() *DistributedDatabasePrivateEndpointList {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabasePrivateEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributedDatabasePrivateEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabasePrivateEndpointSpec) DeepCopyInto(out *DistributedDatabasePrivateEndpointSpec) {
	*out = *in
	if in.NsgIds != nil {
		in, out := &in.NsgIds, &out.NsgIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabasePrivateEndpointSpec.
func (in *DistributedDatabasePrivateEndpointSpec) DeepCopy() *DistributedDatabasePrivateEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabasePrivateEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabasePrivateEndpointStatus) DeepCopyInto(out *DistributedDatabasePrivateEndpointStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	if in.NsgIds != nil {
		in, out := &in.NsgIds, &out.NsgIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GloballyDistributedDatabases != nil {
		in, out := &in.GloballyDistributedDatabases, &out.GloballyDistributedDatabases
		*out = make([]DistributedDatabasePrivateEndpointGloballyDistributedDatabase, len(*in))
		copy(*out, *in)
	}
	if in.GloballyDistributedAutonomousDatabases != nil {
		in, out := &in.GloballyDistributedAutonomousDatabases, &out.GloballyDistributedAutonomousDatabases
		*out = make([]DistributedDatabasePrivateEndpointGloballyDistributedAutonomousDatabase, len(*in))
		copy(*out, *in)
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabasePrivateEndpointStatus.
func (in *DistributedDatabasePrivateEndpointStatus) DeepCopy() *DistributedDatabasePrivateEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabasePrivateEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseShardDetail) DeepCopyInto(out *DistributedDatabaseShardDetail) {
	*out = *in
	out.DbStorageVaultDetails = in.DbStorageVaultDetails
	in.VmClusterDetails.DeepCopyInto(&out.VmClusterDetails)
	if in.PeerDetails != nil {
		in, out := &in.PeerDetails, &out.PeerDetails
		*out = make([]DistributedDatabaseShardDetailPeerDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PeerVmClusterIds != nil {
		in, out := &in.PeerVmClusterIds, &out.PeerVmClusterIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseShardDetail.
func (in *DistributedDatabaseShardDetail) DeepCopy() *DistributedDatabaseShardDetail {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseShardDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseShardDetailDbStorageVaultDetails) DeepCopyInto(out *DistributedDatabaseShardDetailDbStorageVaultDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseShardDetailDbStorageVaultDetails.
func (in *DistributedDatabaseShardDetailDbStorageVaultDetails) DeepCopy() *DistributedDatabaseShardDetailDbStorageVaultDetails {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseShardDetailDbStorageVaultDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseShardDetailMetadata) DeepCopyInto(out *DistributedDatabaseShardDetailMetadata) {
	*out = *in
	if in.PropertiesMap != nil {
		in, out := &in.PropertiesMap, &out.PropertiesMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseShardDetailMetadata.
func (in *DistributedDatabaseShardDetailMetadata) DeepCopy() *DistributedDatabaseShardDetailMetadata {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseShardDetailMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseShardDetailPeerDetail) DeepCopyInto(out *DistributedDatabaseShardDetailPeerDetail) {
	*out = *in
	out.DbStorageVaultDetails = in.DbStorageVaultDetails
	in.VmClusterDetails.DeepCopyInto(&out.VmClusterDetails)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseShardDetailPeerDetail.
func (in *DistributedDatabaseShardDetailPeerDetail) DeepCopy() *DistributedDatabaseShardDetailPeerDetail {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseShardDetailPeerDetail)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseShardDetailPeerDetailDbStorageVaultDetails) DeepCopyInto(out *DistributedDatabaseShardDetailPeerDetailDbStorageVaultDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseShardDetailPeerDetailDbStorageVaultDetails.
func (in *DistributedDatabaseShardDetailPeerDetailDbStorageVaultDetails) DeepCopy() *DistributedDatabaseShardDetailPeerDetailDbStorageVaultDetails {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseShardDetailPeerDetailDbStorageVaultDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseShardDetailPeerDetailMetadata) DeepCopyInto(out *DistributedDatabaseShardDetailPeerDetailMetadata) {
	*out = *in
	if in.PropertiesMap != nil {
		in, out := &in.PropertiesMap, &out.PropertiesMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseShardDetailPeerDetailMetadata.
func (in *DistributedDatabaseShardDetailPeerDetailMetadata) DeepCopy() *DistributedDatabaseShardDetailPeerDetailMetadata {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseShardDetailPeerDetailMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseShardDetailPeerDetailVmClusterDetails) DeepCopyInto(out *DistributedDatabaseShardDetailPeerDetailVmClusterDetails) {
	*out = *in
	if in.SshPublicKeys != nil {
		in, out := &in.SshPublicKeys, &out.SshPublicKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NsgIds != nil {
		in, out := &in.NsgIds, &out.NsgIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BackupNetworkNsgIds != nil {
		in, out := &in.BackupNetworkNsgIds, &out.BackupNetworkNsgIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseShardDetailPeerDetailVmClusterDetails.
func (in *DistributedDatabaseShardDetailPeerDetailVmClusterDetails) DeepCopy() *DistributedDatabaseShardDetailPeerDetailVmClusterDetails {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseShardDetailPeerDetailVmClusterDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseShardDetailVmClusterDetails) DeepCopyInto(out *DistributedDatabaseShardDetailVmClusterDetails) {
	*out = *in
	if in.SshPublicKeys != nil {
		in, out := &in.SshPublicKeys, &out.SshPublicKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NsgIds != nil {
		in, out := &in.NsgIds, &out.NsgIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BackupNetworkNsgIds != nil {
		in, out := &in.BackupNetworkNsgIds, &out.BackupNetworkNsgIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseShardDetailVmClusterDetails.
func (in *DistributedDatabaseShardDetailVmClusterDetails) DeepCopy() *DistributedDatabaseShardDetailVmClusterDetails {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseShardDetailVmClusterDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseSpec) DeepCopyInto(out *DistributedDatabaseSpec) {
	*out = *in
	if in.PrivateEndpointIds != nil {
		in, out := &in.PrivateEndpointIds, &out.PrivateEndpointIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ShardDetails != nil {
		in, out := &in.ShardDetails, &out.ShardDetails
		*out = make([]DistributedDatabaseShardDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CatalogDetails != nil {
		in, out := &in.CatalogDetails, &out.CatalogDetails
		*out = make([]DistributedDatabaseCatalogDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.DbBackupConfig.DeepCopyInto(&out.DbBackupConfig)
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseSpec.
func (in *DistributedDatabaseSpec) DeepCopy() *DistributedDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseStatus) DeepCopyInto(out *DistributedDatabaseStatus) {
	*out = *in
	in.OsokStatus.DeepCopyInto(&out.OsokStatus)
	if in.PrivateEndpointIds != nil {
		in, out := &in.PrivateEndpointIds, &out.PrivateEndpointIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ConnectionStrings.DeepCopyInto(&out.ConnectionStrings)
	out.LatestGsmImageDetails = in.LatestGsmImageDetails
	if in.ShardDetails != nil {
		in, out := &in.ShardDetails, &out.ShardDetails
		*out = make([]DistributedDatabaseShardDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CatalogDetails != nil {
		in, out := &in.CatalogDetails, &out.CatalogDetails
		*out = make([]DistributedDatabaseCatalogDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GsmDetails != nil {
		in, out := &in.GsmDetails, &out.GsmDetails
		*out = make([]DistributedDatabaseGsmDetail, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.DbBackupConfig.DeepCopyInto(&out.DbBackupConfig)
	in.Metadata.DeepCopyInto(&out.Metadata)
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]shared.MapValue, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(shared.MapValue, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseStatus.
func (in *DistributedDatabaseStatus) DeepCopy() *DistributedDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}
