/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package jms

import (
	"context"

	jmsv1beta1 "github.com/oracle/oci-service-operator/api/jms/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// JmsPluginReconciler reconciles a JmsPlugin object.
type JmsPluginReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=jms.oracle.com,resources=jmsplugins,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=jms.oracle.com,resources=jmsplugins/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=jms.oracle.com,resources=jmsplugins/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *JmsPluginReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	jmsPlugin := &jmsv1beta1.JmsPlugin{}
	return r.Reconciler.Reconcile(ctx, req, jmsPlugin)
}

// SetupWithManager sets up the controller with the Manager.
func (r *JmsPluginReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&jmsv1beta1.JmsPlugin{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
