apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oci-service-operator-database-system
namePrefix: oci-service-operator-database-
resources:
- generated/crd
- generated/rbac
- ../../../config/manager/database
- ../../../config/rbac/role_binding.yaml
- ../../../config/rbac/leader_election_role.yaml
- ../../../config/rbac/leader_election_role_binding.yaml
- ../../../config/rbac/autonomousdatabases_editor_role.yaml
- ../../../config/rbac/autonomousdatabases_viewer_role.yaml
- ../../../config/webhook
- ../../../config/certmanager


patches:
  - path: ../../../config/default/webhookcainjection_patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: webhook-cert
          secret:
            secretName: webhook-server-cert
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: webhook-cert
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
