/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package distributeddatabase

import (
	"context"

	distributeddatabasev1beta1 "github.com/oracle/oci-service-operator/api/distributeddatabase/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DistributedDatabaseReconciler reconciles a DistributedDatabase object.
type DistributedDatabaseReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=distributeddatabase.oracle.com,resources=distributeddatabases,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=distributeddatabase.oracle.com,resources=distributeddatabases/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=distributeddatabase.oracle.com,resources=distributeddatabases/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *DistributedDatabaseReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	distributedDatabase := &distributeddatabasev1beta1.DistributedDatabase{}
	return r.Reconciler.Reconcile(ctx, req, distributedDatabase)
}

// SetupWithManager sets up the controller with the Manager.
func (r *DistributedDatabaseReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&distributeddatabasev1beta1.DistributedDatabase{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
