/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package drplan

import (
	"context"
	"fmt"

	disasterrecoverysdk "github.com/oracle/oci-go-sdk/v65/disasterrecovery"
	disasterrecoveryv1beta1 "github.com/oracle/oci-service-operator/api/disasterrecovery/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DrPlanServiceClient is the handwritten extension seam for DrPlan runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*DrPlanServiceManager).WithClient.
type DrPlanServiceClient interface {
	CreateOrUpdate(context.Context, *disasterrecoveryv1beta1.DrPlan, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *disasterrecoveryv1beta1.DrPlan) (bool, error)
}

type defaultDrPlanServiceClient struct {
	generatedruntime.ServiceClient[*disasterrecoveryv1beta1.DrPlan]
}

var _ DrPlanServiceClient = defaultDrPlanServiceClient{}

var newDrPlanServiceClient = func(manager *DrPlanServiceManager) DrPlanServiceClient {
	sdkClient, err := disasterrecoverysdk.NewDisasterRecoveryClientWithConfigurationProvider(manager.Provider)
	hooks := newDrPlanRuntimeHooks(manager, sdkClient)
	config := buildDrPlanGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize DrPlan OCI client: %w", err)
	}
	delegate := defaultDrPlanServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*disasterrecoveryv1beta1.DrPlan](config),
	}
	return wrapDrPlanGeneratedClient(hooks, delegate)
}
