/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package mediaworkflowconfiguration

import (
	"context"
	"fmt"

	mediaservicessdk "github.com/oracle/oci-go-sdk/v65/mediaservices"
	mediaservicesv1beta1 "github.com/oracle/oci-service-operator/api/mediaservices/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// MediaWorkflowConfigurationServiceClient is the handwritten extension seam for MediaWorkflowConfiguration runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*MediaWorkflowConfigurationServiceManager).WithClient.
type MediaWorkflowConfigurationServiceClient interface {
	CreateOrUpdate(context.Context, *mediaservicesv1beta1.MediaWorkflowConfiguration, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *mediaservicesv1beta1.MediaWorkflowConfiguration) (bool, error)
}

type defaultMediaWorkflowConfigurationServiceClient struct {
	generatedruntime.ServiceClient[*mediaservicesv1beta1.MediaWorkflowConfiguration]
}

var _ MediaWorkflowConfigurationServiceClient = defaultMediaWorkflowConfigurationServiceClient{}

var newMediaWorkflowConfigurationServiceClient = func(manager *MediaWorkflowConfigurationServiceManager) MediaWorkflowConfigurationServiceClient {
	sdkClient, err := mediaservicessdk.NewMediaServicesClientWithConfigurationProvider(manager.Provider)
	hooks := newMediaWorkflowConfigurationRuntimeHooks(manager, sdkClient)
	config := buildMediaWorkflowConfigurationGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize MediaWorkflowConfiguration OCI client: %w", err)
	}
	delegate := defaultMediaWorkflowConfigurationServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*mediaservicesv1beta1.MediaWorkflowConfiguration](config),
	}
	return wrapMediaWorkflowConfigurationGeneratedClient(hooks, delegate)
}
