/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package mediaworkflowconfiguration

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	mediaservicesv1beta1 "github.com/oracle/oci-service-operator/api/mediaservices/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type MediaWorkflowConfigurationServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client MediaWorkflowConfigurationServiceClient
}

var _ servicemanager.OSOKServiceManager = (*MediaWorkflowConfigurationServiceManager)(nil)

func NewMediaWorkflowConfigurationServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *MediaWorkflowConfigurationServiceManager {
	manager := &MediaWorkflowConfigurationServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newMediaWorkflowConfigurationServiceClient(manager)
	return manager
}

func NewMediaWorkflowConfigurationServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *MediaWorkflowConfigurationServiceManager {
	return NewMediaWorkflowConfigurationServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *MediaWorkflowConfigurationServiceManager) WithClient(client MediaWorkflowConfigurationServiceClient) *MediaWorkflowConfigurationServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *MediaWorkflowConfigurationServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *MediaWorkflowConfigurationServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *MediaWorkflowConfigurationServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *MediaWorkflowConfigurationServiceManager) convert(obj runtime.Object) (*mediaservicesv1beta1.MediaWorkflowConfiguration, error) {
	resource, ok := obj.(*mediaservicesv1beta1.MediaWorkflowConfiguration)
	if !ok {
		return nil, fmt.Errorf("expected *mediaservicesv1beta1.MediaWorkflowConfiguration, got %T", obj)
	}
	return resource, nil
}

func (c *MediaWorkflowConfigurationServiceManager) status(resource *mediaservicesv1beta1.MediaWorkflowConfiguration) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
