/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package mediaworkflowconfiguration

import (
	"context"

	mediaservicessdk "github.com/oracle/oci-go-sdk/v65/mediaservices"
	mediaservicesv1beta1 "github.com/oracle/oci-service-operator/api/mediaservices/v1beta1"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
)

type runtimeOperationHooks[Req any, Resp any] struct {
	Fields []generatedruntime.RequestField
	Call   func(context.Context, Req) (Resp, error)
}

type MediaWorkflowConfigurationRuntimeHooks struct {
	Semantics       *generatedruntime.Semantics
	BuildCreateBody func(context.Context, *mediaservicesv1beta1.MediaWorkflowConfiguration, string) (any, error)
	BuildUpdateBody func(context.Context, *mediaservicesv1beta1.MediaWorkflowConfiguration, string, any) (any, bool, error)
	// Identity owns bounded pre-create guard and identity reuse hooks.
	Identity            generatedruntime.IdentityHooks[*mediaservicesv1beta1.MediaWorkflowConfiguration]
	Read                generatedruntime.ReadHooks
	TrackedRecreate     generatedruntime.TrackedRecreateHooks[*mediaservicesv1beta1.MediaWorkflowConfiguration]
	StatusHooks         generatedruntime.StatusHooks[*mediaservicesv1beta1.MediaWorkflowConfiguration]
	ParityHooks         generatedruntime.ParityHooks[*mediaservicesv1beta1.MediaWorkflowConfiguration]
	Async               generatedruntime.AsyncHooks[*mediaservicesv1beta1.MediaWorkflowConfiguration]
	DeleteHooks         generatedruntime.DeleteHooks[*mediaservicesv1beta1.MediaWorkflowConfiguration]
	Create              runtimeOperationHooks[mediaservicessdk.CreateMediaWorkflowConfigurationRequest, mediaservicessdk.CreateMediaWorkflowConfigurationResponse]
	Get                 runtimeOperationHooks[mediaservicessdk.GetMediaWorkflowConfigurationRequest, mediaservicessdk.GetMediaWorkflowConfigurationResponse]
	List                runtimeOperationHooks[mediaservicessdk.ListMediaWorkflowConfigurationsRequest, mediaservicessdk.ListMediaWorkflowConfigurationsResponse]
	Update              runtimeOperationHooks[mediaservicessdk.UpdateMediaWorkflowConfigurationRequest, mediaservicessdk.UpdateMediaWorkflowConfigurationResponse]
	Delete              runtimeOperationHooks[mediaservicessdk.DeleteMediaWorkflowConfigurationRequest, mediaservicessdk.DeleteMediaWorkflowConfigurationResponse]
	WrapGeneratedClient []func(MediaWorkflowConfigurationServiceClient) MediaWorkflowConfigurationServiceClient
}

type MediaWorkflowConfigurationRuntimeHooksMutator func(*MediaWorkflowConfigurationServiceManager, *MediaWorkflowConfigurationRuntimeHooks)

var mediaworkflowconfigurationRuntimeHooksMutators []MediaWorkflowConfigurationRuntimeHooksMutator

func registerMediaWorkflowConfigurationRuntimeHooksMutator(mutator MediaWorkflowConfigurationRuntimeHooksMutator) {
	if mutator == nil {
		return
	}
	mediaworkflowconfigurationRuntimeHooksMutators = append(mediaworkflowconfigurationRuntimeHooksMutators, mutator)
}
func newMediaWorkflowConfigurationRuntimeSemantics() *generatedruntime.Semantics {
	return &generatedruntime.Semantics{
		FormalService: "mediaservices",
		FormalSlug:    "mediaworkflowconfiguration",
		Async: &generatedruntime.AsyncSemantics{
			Strategy:             "lifecycle",
			Runtime:              "generatedruntime",
			FormalClassification: "lifecycle",
		},
		StatusProjection:  "required",
		SecretSideEffects: "none",
		FinalizerPolicy:   "retain-until-confirmed-delete",
		Lifecycle: generatedruntime.LifecycleSemantics{
			ProvisioningStates: []string{},
			UpdatingStates:     []string{},
			ActiveStates:       []string{"ACTIVE"},
		},
		Delete: generatedruntime.DeleteSemantics{
			Policy:         "required",
			PendingStates:  []string{},
			TerminalStates: []string{"DELETED", "NOT_FOUND"},
		},
		List: &generatedruntime.ListSemantics{
			ResponseItemsField: "Items",
			MatchFields:        []string{"compartmentId", "displayName"},
		},
		Mutation: generatedruntime.MutationSemantics{
			Mutable:       []string{"definedTags", "displayName", "freeformTags", "parameters"},
			ForceNew:      []string{"compartmentId"},
			ConflictsWith: map[string][]string{},
		},
		Hooks: generatedruntime.HookSet{
			Create: []generatedruntime.Hook{{Helper: "tfresource.CreateResource", EntityType: "", Action: ""}},
			Update: []generatedruntime.Hook{{Helper: "tfresource.UpdateResource", EntityType: "", Action: ""}},
			Delete: []generatedruntime.Hook{{Helper: "tfresource.DeleteResource", EntityType: "", Action: ""}},
		},
		CreateFollowUp: generatedruntime.FollowUpSemantics{
			Strategy: "read-after-write",
			Hooks:    []generatedruntime.Hook{{Helper: "tfresource.CreateResource", EntityType: "", Action: ""}},
		},
		UpdateFollowUp: generatedruntime.FollowUpSemantics{
			Strategy: "read-after-write",
			Hooks:    []generatedruntime.Hook{{Helper: "tfresource.UpdateResource", EntityType: "", Action: ""}},
		},
		DeleteFollowUp: generatedruntime.FollowUpSemantics{
			Strategy: "confirm-delete",
			Hooks:    []generatedruntime.Hook{{Helper: "tfresource.DeleteResource", EntityType: "", Action: ""}},
		},
		AuxiliaryOperations: []generatedruntime.AuxiliaryOperation{},
		Unsupported:         []generatedruntime.UnsupportedSemantic{},
	}
}
func newMediaWorkflowConfigurationDefaultRuntimeHooks(sdkClient mediaservicessdk.MediaServicesClient) MediaWorkflowConfigurationRuntimeHooks {
	return MediaWorkflowConfigurationRuntimeHooks{
		Semantics:       newMediaWorkflowConfigurationRuntimeSemantics(),
		Identity:        generatedruntime.IdentityHooks[*mediaservicesv1beta1.MediaWorkflowConfiguration]{},
		Read:            generatedruntime.ReadHooks{},
		TrackedRecreate: generatedruntime.TrackedRecreateHooks[*mediaservicesv1beta1.MediaWorkflowConfiguration]{},
		StatusHooks:     generatedruntime.StatusHooks[*mediaservicesv1beta1.MediaWorkflowConfiguration]{},
		ParityHooks:     generatedruntime.ParityHooks[*mediaservicesv1beta1.MediaWorkflowConfiguration]{},
		Async:           generatedruntime.AsyncHooks[*mediaservicesv1beta1.MediaWorkflowConfiguration]{},
		DeleteHooks:     generatedruntime.DeleteHooks[*mediaservicesv1beta1.MediaWorkflowConfiguration]{},
		Create: runtimeOperationHooks[mediaservicessdk.CreateMediaWorkflowConfigurationRequest, mediaservicessdk.CreateMediaWorkflowConfigurationResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CreateMediaWorkflowConfigurationDetails", RequestName: "CreateMediaWorkflowConfigurationDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request mediaservicessdk.CreateMediaWorkflowConfigurationRequest) (mediaservicessdk.CreateMediaWorkflowConfigurationResponse, error) {
				return sdkClient.CreateMediaWorkflowConfiguration(ctx, request)
			},
		},
		Get: runtimeOperationHooks[mediaservicessdk.GetMediaWorkflowConfigurationRequest, mediaservicessdk.GetMediaWorkflowConfigurationResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "MediaWorkflowConfigurationId", RequestName: "mediaWorkflowConfigurationId", Contribution: "path", PreferResourceID: true}},
			Call: func(ctx context.Context, request mediaservicessdk.GetMediaWorkflowConfigurationRequest) (mediaservicessdk.GetMediaWorkflowConfigurationResponse, error) {
				return sdkClient.GetMediaWorkflowConfiguration(ctx, request)
			},
		},
		List: runtimeOperationHooks[mediaservicessdk.ListMediaWorkflowConfigurationsRequest, mediaservicessdk.ListMediaWorkflowConfigurationsResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "CompartmentId", RequestName: "compartmentId", Contribution: "query", PreferResourceID: false}, {FieldName: "LifecycleState", RequestName: "lifecycleState", Contribution: "query", PreferResourceID: false}, {FieldName: "DisplayName", RequestName: "displayName", Contribution: "query", PreferResourceID: false}, {FieldName: "Id", RequestName: "id", Contribution: "query", PreferResourceID: false}, {FieldName: "Limit", RequestName: "limit", Contribution: "query", PreferResourceID: false}, {FieldName: "Page", RequestName: "page", Contribution: "query", PreferResourceID: false}, {FieldName: "SortOrder", RequestName: "sortOrder", Contribution: "query", PreferResourceID: false}, {FieldName: "SortBy", RequestName: "sortBy", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request mediaservicessdk.ListMediaWorkflowConfigurationsRequest) (mediaservicessdk.ListMediaWorkflowConfigurationsResponse, error) {
				return sdkClient.ListMediaWorkflowConfigurations(ctx, request)
			},
		},
		Update: runtimeOperationHooks[mediaservicessdk.UpdateMediaWorkflowConfigurationRequest, mediaservicessdk.UpdateMediaWorkflowConfigurationResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "MediaWorkflowConfigurationId", RequestName: "mediaWorkflowConfigurationId", Contribution: "path", PreferResourceID: true}, {FieldName: "IsLockOverride", RequestName: "isLockOverride", Contribution: "query", PreferResourceID: false}, {FieldName: "UpdateMediaWorkflowConfigurationDetails", RequestName: "UpdateMediaWorkflowConfigurationDetails", Contribution: "body", PreferResourceID: false}},
			Call: func(ctx context.Context, request mediaservicessdk.UpdateMediaWorkflowConfigurationRequest) (mediaservicessdk.UpdateMediaWorkflowConfigurationResponse, error) {
				return sdkClient.UpdateMediaWorkflowConfiguration(ctx, request)
			},
		},
		Delete: runtimeOperationHooks[mediaservicessdk.DeleteMediaWorkflowConfigurationRequest, mediaservicessdk.DeleteMediaWorkflowConfigurationResponse]{
			Fields: []generatedruntime.RequestField{{FieldName: "MediaWorkflowConfigurationId", RequestName: "mediaWorkflowConfigurationId", Contribution: "path", PreferResourceID: true}, {FieldName: "IsLockOverride", RequestName: "isLockOverride", Contribution: "query", PreferResourceID: false}},
			Call: func(ctx context.Context, request mediaservicessdk.DeleteMediaWorkflowConfigurationRequest) (mediaservicessdk.DeleteMediaWorkflowConfigurationResponse, error) {
				return sdkClient.DeleteMediaWorkflowConfiguration(ctx, request)
			},
		},
		WrapGeneratedClient: []func(MediaWorkflowConfigurationServiceClient) MediaWorkflowConfigurationServiceClient{},
	}
}

func newMediaWorkflowConfigurationRuntimeHooks(manager *MediaWorkflowConfigurationServiceManager, sdkClient mediaservicessdk.MediaServicesClient) MediaWorkflowConfigurationRuntimeHooks {
	hooks := newMediaWorkflowConfigurationDefaultRuntimeHooks(sdkClient)
	for _, mutator := range mediaworkflowconfigurationRuntimeHooksMutators {
		mutator(manager, &hooks)
	}
	return hooks
}

func buildMediaWorkflowConfigurationGeneratedRuntimeConfig(
	manager *MediaWorkflowConfigurationServiceManager,
	hooks MediaWorkflowConfigurationRuntimeHooks,
) generatedruntime.Config[*mediaservicesv1beta1.MediaWorkflowConfiguration] {
	return generatedruntime.Config[*mediaservicesv1beta1.MediaWorkflowConfiguration]{
		Kind:            "MediaWorkflowConfiguration",
		SDKName:         "MediaWorkflowConfiguration",
		Log:             manager.Log,
		Semantics:       hooks.Semantics,
		Identity:        hooks.Identity,
		Read:            hooks.Read,
		TrackedRecreate: hooks.TrackedRecreate,
		StatusHooks:     hooks.StatusHooks,
		ParityHooks:     hooks.ParityHooks,
		Async:           hooks.Async,
		DeleteHooks:     hooks.DeleteHooks,
		BuildCreateBody: hooks.BuildCreateBody,
		BuildUpdateBody: hooks.BuildUpdateBody,
		Create: &generatedruntime.Operation{
			NewRequest: func() any { return &mediaservicessdk.CreateMediaWorkflowConfigurationRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Create.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Create.Call(ctx, *request.(*mediaservicessdk.CreateMediaWorkflowConfigurationRequest))
			},
		},
		Get: &generatedruntime.Operation{
			NewRequest: func() any { return &mediaservicessdk.GetMediaWorkflowConfigurationRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Get.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Get.Call(ctx, *request.(*mediaservicessdk.GetMediaWorkflowConfigurationRequest))
			},
		},
		List: &generatedruntime.Operation{
			NewRequest: func() any { return &mediaservicessdk.ListMediaWorkflowConfigurationsRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.List.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.List.Call(ctx, *request.(*mediaservicessdk.ListMediaWorkflowConfigurationsRequest))
			},
		},
		Update: &generatedruntime.Operation{
			NewRequest: func() any { return &mediaservicessdk.UpdateMediaWorkflowConfigurationRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Update.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Update.Call(ctx, *request.(*mediaservicessdk.UpdateMediaWorkflowConfigurationRequest))
			},
		},
		Delete: &generatedruntime.Operation{
			NewRequest: func() any { return &mediaservicessdk.DeleteMediaWorkflowConfigurationRequest{} },
			Fields:     append([]generatedruntime.RequestField(nil), hooks.Delete.Fields...),
			Call: func(ctx context.Context, request any) (any, error) {
				return hooks.Delete.Call(ctx, *request.(*mediaservicessdk.DeleteMediaWorkflowConfigurationRequest))
			},
		},
	}
}

func wrapMediaWorkflowConfigurationGeneratedClient(
	hooks MediaWorkflowConfigurationRuntimeHooks,
	delegate MediaWorkflowConfigurationServiceClient,
) MediaWorkflowConfigurationServiceClient {
	wrapped := delegate
	for _, wrap := range hooks.WrapGeneratedClient {
		if wrap == nil {
			continue
		}
		wrapped = wrap(wrapped)
	}
	return wrapped
}
