/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package generativeaiagent

import (
	"context"

	generativeaiagentv1beta1 "github.com/oracle/oci-service-operator/api/generativeaiagent/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// AgentEndpointReconciler reconciles a AgentEndpoint object.
type AgentEndpointReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=generativeaiagent.oracle.com,resources=agentendpoints,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=generativeaiagent.oracle.com,resources=agentendpoints/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=generativeaiagent.oracle.com,resources=agentendpoints/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *AgentEndpointReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	agentEndpoint := &generativeaiagentv1beta1.AgentEndpoint{}
	return r.Reconciler.Reconcile(ctx, req, agentEndpoint)
}

// SetupWithManager sets up the controller with the Manager.
func (r *AgentEndpointReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&generativeaiagentv1beta1.AgentEndpoint{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
