/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package v1beta1

import (
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DomainGovernanceSpec defines the desired state of DomainGovernance.
type DomainGovernanceSpec struct {
	// OCID of the tenancy.
	// +kubebuilder:validation:Required
	CompartmentId string `json:"compartmentId"`
	// OCID of the domain.
	// +kubebuilder:validation:Required
	DomainId string `json:"domainId"`
	// Email address to be used to notify the user, and that the ONS subscription will be created with.
	// +kubebuilder:validation:Required
	SubscriptionEmail string `json:"subscriptionEmail"`
	// The ONS topic associated with this domain governance entity.
	// +kubebuilder:validation:Required
	OnsTopicId string `json:"onsTopicId"`
	// The ONS subscription associated with this domain governance entity.
	// +kubebuilder:validation:Required
	OnsSubscriptionId string `json:"onsSubscriptionId"`
	// Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
	// Example: `{"bar-key": "value"}`
	// +kubebuilder:validation:Optional
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"foo-namespace": {"bar-key": "value"}}`
	// +kubebuilder:validation:Optional
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// Indicates whether governance is enabled for this domain.
	// +kubebuilder:validation:Optional
	IsGovernanceEnabled bool `json:"isGovernanceEnabled,omitempty"`
}

// DomainGovernanceStatus defines the observed state of DomainGovernance.
type DomainGovernanceStatus struct {
	OsokStatus shared.OSOKStatus `json:"status"`
	// The OCID of the domain governance entity.
	Id string `json:"id,omitempty"`
	// The OCID of the tenancy that owns this domain governance entity.
	OwnerId string `json:"ownerId,omitempty"`
	// The OCID of the domain associated with this domain governance entity.
	DomainId string `json:"domainId,omitempty"`
	// Lifecycle state of the domain governance entity.
	LifecycleState string `json:"lifecycleState,omitempty"`
	// The ONS topic associated with this domain governance entity.
	OnsTopicId string `json:"onsTopicId,omitempty"`
	// The ONS subscription associated with this domain governance entity.
	OnsSubscriptionId string `json:"onsSubscriptionId,omitempty"`
	// Indicates whether governance is enabled for this domain.
	IsGovernanceEnabled bool `json:"isGovernanceEnabled,omitempty"`
	// Email address to be used to notify the user, and that the ONS subscription will be created with.
	SubscriptionEmail string `json:"subscriptionEmail,omitempty"`
	// Date-time when this domain governance was created. An RFC 3339-formatted date and time string.
	TimeCreated string `json:"timeCreated,omitempty"`
	// Date-time when this domain governance was last updated. An RFC 3339-formatted date and time string.
	TimeUpdated string `json:"timeUpdated,omitempty"`
	// Simple key-value pair that is applied without any predefined name, type or scope. Exists for cross-compatibility only.
	// Example: `{"bar-key": "value"}`
	FreeformTags map[string]string `json:"freeformTags,omitempty"`
	// Defined tags for this resource. Each key is predefined and scoped to a namespace.
	// Example: `{"foo-namespace": {"bar-key": "value"}}`
	DefinedTags map[string]shared.MapValue `json:"definedTags,omitempty"`
	// Usage of system tag keys. These predefined keys are scoped to namespaces.
	// Example: `{"orcl-cloud": {"free-tier-retained": "true"}}`
	SystemTags map[string]shared.MapValue `json:"systemTags,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.status.conditions[-1].type",description="status of the DomainGovernance",priority=0
// +kubebuilder:printcolumn:name="Ocid",type="string",JSONPath=".status.status.ocid",description="Ocid of the DomainGovernance",priority=1
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp",priority=0
// DomainGovernance is the Schema for the domaingovernances API.
type DomainGovernance struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DomainGovernanceSpec   `json:"spec,omitempty"`
	Status DomainGovernanceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
// DomainGovernanceList contains a list of DomainGovernance.
type DomainGovernanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DomainGovernance `json:"items"`
}

func init() {
	SchemeBuilder.Register(&DomainGovernance{}, &DomainGovernanceList{})
}
