/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package tenantmanagercontrolplane

import (
	"context"

	tenantmanagercontrolplanev1beta1 "github.com/oracle/oci-service-operator/api/tenantmanagercontrolplane/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/core"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DomainGovernanceReconciler reconciles a DomainGovernance object.
type DomainGovernanceReconciler struct {
	Reconciler *core.BaseReconciler
}

// +kubebuilder:rbac:groups=tenantmanagercontrolplane.oracle.com,resources=domaingovernances,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=tenantmanagercontrolplane.oracle.com,resources=domaingovernances/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=tenantmanagercontrolplane.oracle.com,resources=domaingovernances/finalizers,verbs=update
// +kubebuilder:rbac:groups="",resources=events,verbs=create;patch

// Reconcile is part of the main Kubernetes reconciliation loop.
func (r *DomainGovernanceReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	domainGovernance := &tenantmanagercontrolplanev1beta1.DomainGovernance{}
	return r.Reconciler.Reconcile(ctx, req, domainGovernance)
}

// SetupWithManager sets up the controller with the Manager.
func (r *DomainGovernanceReconciler) SetupWithManager(mgr ctrl.Manager) error {
	builder := ctrl.NewControllerManagedBy(mgr).
		For(&tenantmanagercontrolplanev1beta1.DomainGovernance{})
	return builder.
		WithEventFilter(core.ReconcilePredicate()).
		Complete(r)
}
