apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: __OSOK_MANAGER_ROLE_BINDING_NAME__
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: __OSOK_MANAGER_ROLE_NAME__
subjects:
  - kind: ServiceAccount
    name: {{ include "osok.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: __OSOK_LEADER_ROLE_BINDING_NAME__
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: __OSOK_LEADER_ROLE_NAME__
subjects:
  - kind: ServiceAccount
    name: {{ include "osok.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
