/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package agentendpoint

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	generativeaiagentv1beta1 "github.com/oracle/oci-service-operator/api/generativeaiagent/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type AgentEndpointServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client AgentEndpointServiceClient
}

var _ servicemanager.OSOKServiceManager = (*AgentEndpointServiceManager)(nil)

func NewAgentEndpointServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *AgentEndpointServiceManager {
	manager := &AgentEndpointServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newAgentEndpointServiceClient(manager)
	return manager
}

func NewAgentEndpointServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *AgentEndpointServiceManager {
	return NewAgentEndpointServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *AgentEndpointServiceManager) WithClient(client AgentEndpointServiceClient) *AgentEndpointServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *AgentEndpointServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *AgentEndpointServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *AgentEndpointServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *AgentEndpointServiceManager) convert(obj runtime.Object) (*generativeaiagentv1beta1.AgentEndpoint, error) {
	resource, ok := obj.(*generativeaiagentv1beta1.AgentEndpoint)
	if !ok {
		return nil, fmt.Errorf("expected *generativeaiagentv1beta1.AgentEndpoint, got %T", obj)
	}
	return resource, nil
}

func (c *AgentEndpointServiceManager) status(resource *generativeaiagentv1beta1.AgentEndpoint) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
