/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package agentendpoint

import (
	"context"
	"fmt"

	generativeaiagentsdk "github.com/oracle/oci-go-sdk/v65/generativeaiagent"
	generativeaiagentv1beta1 "github.com/oracle/oci-service-operator/api/generativeaiagent/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// AgentEndpointServiceClient is the handwritten extension seam for AgentEndpoint runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*AgentEndpointServiceManager).WithClient.
type AgentEndpointServiceClient interface {
	CreateOrUpdate(context.Context, *generativeaiagentv1beta1.AgentEndpoint, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *generativeaiagentv1beta1.AgentEndpoint) (bool, error)
}

type defaultAgentEndpointServiceClient struct {
	generatedruntime.ServiceClient[*generativeaiagentv1beta1.AgentEndpoint]
}

var _ AgentEndpointServiceClient = defaultAgentEndpointServiceClient{}

var newAgentEndpointServiceClient = func(manager *AgentEndpointServiceManager) AgentEndpointServiceClient {
	sdkClient, err := generativeaiagentsdk.NewGenerativeAiAgentClientWithConfigurationProvider(manager.Provider)
	hooks := newAgentEndpointRuntimeHooks(manager, sdkClient)
	config := buildAgentEndpointGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize AgentEndpoint OCI client: %w", err)
	}
	delegate := defaultAgentEndpointServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*generativeaiagentv1beta1.AgentEndpoint](config),
	}
	return wrapAgentEndpointGeneratedClient(hooks, delegate)
}
