/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package distributeddatabase

import (
	"context"
	"fmt"

	"github.com/oracle/oci-go-sdk/v65/common"
	distributeddatabasev1beta1 "github.com/oracle/oci-service-operator/api/distributeddatabase/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/credhelper"
	"github.com/oracle/oci-service-operator/pkg/loggerutil"
	"github.com/oracle/oci-service-operator/pkg/metrics"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	shared "github.com/oracle/oci-service-operator/pkg/shared"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
)

type DistributedDatabaseServiceManager struct {
	Provider         common.ConfigurationProvider
	CredentialClient credhelper.CredentialClient
	Scheme           *runtime.Scheme
	Log              loggerutil.OSOKLogger
	Metrics          *metrics.Metrics

	client DistributedDatabaseServiceClient
}

var _ servicemanager.OSOKServiceManager = (*DistributedDatabaseServiceManager)(nil)

func NewDistributedDatabaseServiceManagerWithDeps(deps servicemanager.RuntimeDeps) *DistributedDatabaseServiceManager {
	manager := &DistributedDatabaseServiceManager{
		Provider:         deps.Provider,
		CredentialClient: deps.CredentialClient,
		Scheme:           deps.Scheme,
		Log:              deps.Log,
		Metrics:          deps.Metrics,
	}
	manager.client = newDistributedDatabaseServiceClient(manager)
	return manager
}

func NewDistributedDatabaseServiceManager(provider common.ConfigurationProvider, credClient credhelper.CredentialClient,
	scheme *runtime.Scheme, log loggerutil.OSOKLogger, metrics *metrics.Metrics) *DistributedDatabaseServiceManager {
	return NewDistributedDatabaseServiceManagerWithDeps(servicemanager.RuntimeDeps{
		Provider:         provider,
		CredentialClient: credClient,
		Scheme:           scheme,
		Log:              log,
		Metrics:          metrics,
	})
}

// WithClient overrides the default generated client with handwritten runtime behavior.
func (c *DistributedDatabaseServiceManager) WithClient(client DistributedDatabaseServiceClient) *DistributedDatabaseServiceManager {
	if client != nil {
		c.client = client
	}
	return c
}

func (c *DistributedDatabaseServiceManager) CreateOrUpdate(ctx context.Context, obj runtime.Object, req ctrl.Request) (servicemanager.OSOKResponse, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return servicemanager.OSOKResponse{IsSuccessful: false}, err
	}

	return c.client.CreateOrUpdate(ctx, resource, req)
}

func (c *DistributedDatabaseServiceManager) Delete(ctx context.Context, obj runtime.Object) (bool, error) {
	resource, err := c.convert(obj)
	if err != nil {
		c.Log.ErrorLog(err, "Conversion of object failed")
		return false, err
	}

	return c.client.Delete(ctx, resource)
}

func (c *DistributedDatabaseServiceManager) GetCrdStatus(obj runtime.Object) (*shared.OSOKStatus, error) {
	resource, err := c.convert(obj)
	if err != nil {
		return nil, err
	}

	return c.status(resource), nil
}

func (c *DistributedDatabaseServiceManager) convert(obj runtime.Object) (*distributeddatabasev1beta1.DistributedDatabase, error) {
	resource, ok := obj.(*distributeddatabasev1beta1.DistributedDatabase)
	if !ok {
		return nil, fmt.Errorf("expected *distributeddatabasev1beta1.DistributedDatabase, got %T", obj)
	}
	return resource, nil
}

func (c *DistributedDatabaseServiceManager) status(resource *distributeddatabasev1beta1.DistributedDatabase) *shared.OSOKStatus {
	return &resource.Status.OsokStatus
}
