/*
  Copyright (c) 2021, Oracle and/or its affiliates. All rights reserved.
  Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
*/

// Code generated by generator. DO NOT EDIT.

package distributeddatabase

import (
	"context"
	"fmt"

	distributeddatabasesdk "github.com/oracle/oci-go-sdk/v65/distributeddatabase"
	distributeddatabasev1beta1 "github.com/oracle/oci-service-operator/api/distributeddatabase/v1beta1"
	"github.com/oracle/oci-service-operator/pkg/servicemanager"
	generatedruntime "github.com/oracle/oci-service-operator/pkg/servicemanager/generatedruntime"
	ctrl "sigs.k8s.io/controller-runtime"
)

// DistributedDatabaseServiceClient is the handwritten extension seam for DistributedDatabase runtime behavior.
// Add a manual file in this package that registers runtime hook mutators or wires a custom client through
// (*DistributedDatabaseServiceManager).WithClient.
type DistributedDatabaseServiceClient interface {
	CreateOrUpdate(context.Context, *distributeddatabasev1beta1.DistributedDatabase, ctrl.Request) (servicemanager.OSOKResponse, error)
	Delete(context.Context, *distributeddatabasev1beta1.DistributedDatabase) (bool, error)
}

type defaultDistributedDatabaseServiceClient struct {
	generatedruntime.ServiceClient[*distributeddatabasev1beta1.DistributedDatabase]
}

var _ DistributedDatabaseServiceClient = defaultDistributedDatabaseServiceClient{}

var newDistributedDatabaseServiceClient = func(manager *DistributedDatabaseServiceManager) DistributedDatabaseServiceClient {
	sdkClient, err := distributeddatabasesdk.NewDistributedDbServiceClientWithConfigurationProvider(manager.Provider)
	hooks := newDistributedDatabaseRuntimeHooks(manager, sdkClient)
	config := buildDistributedDatabaseGeneratedRuntimeConfig(manager, hooks)
	if err != nil {
		config.InitError = fmt.Errorf("initialize DistributedDatabase OCI client: %w", err)
	}
	delegate := defaultDistributedDatabaseServiceClient{
		ServiceClient: generatedruntime.NewServiceClient[*distributeddatabasev1beta1.DistributedDatabase](config),
	}
	return wrapDistributedDatabaseGeneratedClient(hooks, delegate)
}
